project:
  type: book
  resources:
    - img/*
  post-render:
    - cp -R data _book
    - make_student_versions.py

execute:
  freeze: auto

book:
  title: "Quantitative Political Science I"
  author: "Brenton Kenkel"
  date: last-modified
  chapters:
    - index.qmd
    - intro_r.qmd
    - data_wrangling.qmd
    - univariate_analysis.qmd
    - data_visualization.qmd
    - correlation_regression.qmd
    - simulation_resampling.qmd
    - text_analysis.qmd
    - references.qmd
  appendices:
    - using_chatgpt.qmd
    - data_sources.qmd
  license: "CC BY-NC-SA 4.0"
  sidebar:
    style: docked
  page-footer:
    center: |
      <p xmlns:cc="http://creativecommons.org/ns#" class="cc-footer">This work is licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-NC-SA 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1" alt=""></a></p>

bibliography: references.bib

format:
  html:
    theme:
      - lumen
      - qps1.scss
    title-block-banner: false
    monofont: 'Iosevka Web'
    linestretch: 1.6
    cap-location: top
    lightbox: true

