# Preface {.unnumbered}

These are the course notes for Prof. [Brenton Kenkel](https://bkenkel.com)'s course PSCI 2300 (Quantitative Political Science I: Computing) at Vanderbilt University.

PSCI 2300 is an introductory course on data analysis for political science.
The course is intended to get students up and running with R programming and simple data analysis techniques, without going too deeply into math or statistics.
Before using these techniques for high-stakes research, whether in academia or the private sector, you'll want to get deeper coverage from more advanced courses and sources.

These notes are written in [Quarto](https://quarto.org/) and published on [GitHub Pages](https://pages.github.com/).
You can find the Quarto source files [on GitHub](https://github.com/brentonk/qps1).

**Acknowledgments:**
I've taken a lot from lecture notes written by my colleague [Josh Clinton](https://my.vanderbilt.edu/joshclinton/) for prior iterations of PSCI 2300.
My colleague [Jim Bisbee](https://www.jamesbisbee.com/)'s notes for [his offering of DS 1000](https://github.com/jbisbee1/DS1000_S2024) have been helpful too.
I'm also grateful to students from the fall 2024 offering of PSCI 2300 for their suggestions, and to [Nguyen Ha](https://thaonguyen-ha.com/) who gave lots of helpful feedback in her capacity as the TA.
