<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>2&nbsp; Data Wrangling – Quantitative Political Science I</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./univariate_analysis.html" rel="next">
<link href="./intro_r.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-883b25f5fe4cf763c1e99fca87094caa.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar docked slimcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./data_wrangling.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data Wrangling</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Quantitative Political Science I</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro_r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_wrangling.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data Wrangling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./univariate_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Univariate Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data Visualization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./correlation_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Correlation and Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./simulation_resampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Simulation and Resampling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./text_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Text Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./using_chatgpt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Using ChatGPT</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_sources.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Data Sources</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#data-international-crises" id="toc-data-international-crises" class="nav-link active" data-scroll-target="#data-international-crises"><span class="header-section-number">2.1</span> Data: International crises</a></li>
  <li><a href="#subsetting" id="toc-subsetting" class="nav-link" data-scroll-target="#subsetting"><span class="header-section-number">2.2</span> Subsetting</a>
  <ul class="collapse">
  <li><a href="#subsetting-by-column-select" id="toc-subsetting-by-column-select" class="nav-link" data-scroll-target="#subsetting-by-column-select"><span class="header-section-number">2.2.1</span> Subsetting by column: <code>select()</code></a></li>
  <li><a href="#subsetting-by-row-filter" id="toc-subsetting-by-row-filter" class="nav-link" data-scroll-target="#subsetting-by-row-filter"><span class="header-section-number">2.2.2</span> Subsetting by row: <code>filter()</code></a></li>
  <li><a href="#piping-commands-together" id="toc-piping-commands-together" class="nav-link" data-scroll-target="#piping-commands-together"><span class="header-section-number">2.2.3</span> “Piping” commands together</a></li>
  </ul></li>
  <li><a href="#transforming" id="toc-transforming" class="nav-link" data-scroll-target="#transforming"><span class="header-section-number">2.3</span> Transforming</a>
  <ul class="collapse">
  <li><a href="#changing-variables-and-making-new-ones" id="toc-changing-variables-and-making-new-ones" class="nav-link" data-scroll-target="#changing-variables-and-making-new-ones"><span class="header-section-number">2.3.1</span> Changing variables and making new ones</a></li>
  <li><a href="#grouping-and-summarizing" id="toc-grouping-and-summarizing" class="nav-link" data-scroll-target="#grouping-and-summarizing"><span class="header-section-number">2.3.2</span> Grouping and summarizing</a></li>
  </ul></li>
  <li><a href="#reshaping" id="toc-reshaping" class="nav-link" data-scroll-target="#reshaping"><span class="header-section-number">2.4</span> Reshaping</a></li>
  <li><a href="#merging" id="toc-merging" class="nav-link" data-scroll-target="#merging"><span class="header-section-number">2.5</span> Merging</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-data-wrangling" class="quarto-section-identifier"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data Wrangling</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In <a href="intro_r.html" class="quarto-xref"><span>Chapter 1</span></a>, we saw how to get data into R and the basics of writing code in Quarto. Now we’re going to dig further into “wrangling” raw data into a form that’s useful for analysis.</p>
<p>In both academic research and industry data science, the hard part of data analysis usually isn’t the statistical modeling — it’s to acquire the data in the first place, and then to get it into a state that’s clean enough to plug into whatever statistical model you plan to use.</p>
<p>The main data wrangling skills you’re going to pick up here are:</p>
<ol type="1">
<li><p>How to <span class="concept">subset the data</span> to the variables (columns) and observations (rows) that you care about for your analysis. Along the way, you’ll see how to use the most common <span class="concept">logical and comparison operators</span> in scientific computing:</p>
<ul>
<li>equal to: <code>==</code></li>
<li>not equal to: <code>!=</code></li>
<li>greater than: <code>&gt;</code></li>
<li>less than: <code>&lt;</code></li>
<li>not: <code>!</code></li>
<li>and: <code>&amp;</code></li>
<li>or: <code>|</code></li>
</ul></li>
<li><p>Methods to <span class="concept">transform</span> your data: changing variables in place, creating new variables, summarizing variables both for the full data and within subcategories of observations.</p></li>
<li><p>How to <span class="concept">reshape</span> data into “longer” and “wider” formats, which is especially important when your raw data comes to you in a weird or inconvenient shape (more often than you’d like!).</p></li>
<li><p>How to <span class="concept">merge</span> data sets from disparate sources together into a single data frame you can analyze.</p></li>
</ol>
<section id="data-international-crises" class="level2 page-columns page-full" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="data-international-crises"><span class="header-section-number">2.1</span> Data: International crises</h2>
<p>We will work with data from the <a href="https://sites.duke.edu/icbdata/data-collections/">International Crisis Behavior Project</a> on countries involved in international crises. The project’s operational definition of an international crisis is a situation in which there is</p>
<blockquote class="blockquote">
<p>… (1) a change in type and/or an increase in intensity of <em>disruptive</em>, that is, hostile verbal or physical <em>interactions</em> between two or more states, with a heightened probability of <em>military hostilities</em>; that, in turn, (2) destabilizes their relationship and <em>challenges</em> the <em>structure</em> of an international system — global, dominant, or subsystem.</p>
</blockquote>

<div class="no-row-height column-margin column-container"><div class="margin-aside">
<p>Quotation from Michael Brecher and Jonathan Wilkenfeld, <em>A Study of Crisis</em>, pages 4–5.</p>
</div></div><p>To put it more simply, countries are in a state of crisis when something happens that raises tensions between them to the point that there is a legitimate fear of war. Every war starts as a crisis, but not all crises lead to war (and in fact the vast majority do not).</p>
<p>We will work with the ICB Project’s “actor level” dataset, in which each observation (row) is a crisis participant. For example, in the Cuban Missile Crisis of 1962 (crisis #196 in the ICB data), the United States, Cuba, and the Soviet Union are each separate crisis participants. The data is on my website at <a href="https://bkenkel.com/qps1/data/crises.csv" class="uri">https://bkenkel.com/qps1/data/crises.csv</a>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"tidyverse"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>df_crises <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://bkenkel.com/qps1/data/crises.csv"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>df_crises</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,131 × 95
   icb2  crisno cracno cracid actor systrgyr systrgmo systrgda crisname 
   &lt;chr&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;    
 1 ICB2       1      1    365 RUS       1918        5       NA RUSSIAN …
 2 ICB2       2      2     93 NIC       1918        5       25 COSTA RI…
 3 ICB2       2      3     94 COS       1918        5       25 COSTA RI…
 4 ICB2       3      4    365 RUS       1918        6       23 RUSSIAN …
 5 ICB2       4      5    365 RUS       1918       11       18 BALTIC I…
 6 ICB2       4      6    366 EST       1918       11       18 BALTIC I…
 7 ICB2       4      7    368 LIT       1918       11       18 BALTIC I…
 8 ICB2       4      8    367 LAT       1918       11       18 BALTIC I…
 9 ICB2       5      9    315 CZE       1919        1       15 TESCHEN  
10 ICB2       5     10    290 POL       1919        1       15 TESCHEN  
# ℹ 1,121 more rows
# ℹ 86 more variables: triggr &lt;dbl&gt;, yrtrig &lt;dbl&gt;, motrig &lt;dbl&gt;,
#   datrig &lt;dbl&gt;, trigent &lt;dbl&gt;, trigloc &lt;dbl&gt;, southv &lt;dbl&gt;,
#   southpow &lt;dbl&gt;, sizedu &lt;dbl&gt;, strcdu &lt;dbl&gt;, comlev &lt;dbl&gt;,
#   majres &lt;dbl&gt;, yerres &lt;dbl&gt;, monres &lt;dbl&gt;, dayres &lt;dbl&gt;,
#   trgresra &lt;dbl&gt;, crismg &lt;dbl&gt;, cenvio &lt;dbl&gt;, sevvio &lt;dbl&gt;,
#   usinv &lt;dbl&gt;, usfavr &lt;dbl&gt;, suinv &lt;dbl&gt;, sufavr &lt;dbl&gt;, …</code></pre>
</div>
</div>
<p>As you can see, there are a <em>ton</em> of variables here. The ICB Project provides <a href="https://duke.box.com/s/l4glcl5jaipmycs7unzraxkp92w1nh3d">a full codebook</a> describing each variable in the dataset. The most important variables you need to know from the start are:</p>
<ul>
<li><p><code>crisname</code> and <code>crisno</code>: The name of the crisis and a numeric identifier assigned to each separate crisis.</p></li>
<li><p><code>actor</code> and <code>cracid</code>: A country involved in the crisis and a numeric identifier assigned to each different country (e.g., USA = 2, Russia/Soviet Union = 365).</p></li>
<li><p><code>systrgyr</code>: The year the crisis began.</p></li>
</ul>
<p>So for example, the first crisis in the data (<code>crisno</code> = 1) is the Russian Civil War, which only involved Russia. The second (<code>crisno</code> = 2) is a 1918 crisis between Nicaragua and Costa Rica, each of which gets their own row in the data.</p>
</section>
<section id="subsetting" class="level2 page-columns page-full" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="subsetting"><span class="header-section-number">2.2</span> Subsetting</h2>
<section id="subsetting-by-column-select" class="level3" data-number="2.2.1">
<h3 data-number="2.2.1" class="anchored" data-anchor-id="subsetting-by-column-select"><span class="header-section-number">2.2.1</span> Subsetting by column: <code>select()</code></h3>
<p>The <code>select()</code> function lets us reduce the data frame just to have the columns we care about, or even just reorder the columns if you’re not trying to get rid of any data but want things to be arranged differently.</p>
<section id="basic-usage" class="level4" data-number="2.2.1.1">
<h4 data-number="2.2.1.1" class="anchored" data-anchor-id="basic-usage"><span class="header-section-number">2.2.1.1</span> Basic usage</h4>
<p>The simplest way to use <code>select()</code> is to tell it what data frame you’re working with, then list the names of the columns you want to keep from it.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(df_crises, crisname, actor, systrgyr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,131 × 3
   crisname             actor systrgyr
   &lt;chr&gt;                &lt;chr&gt;    &lt;dbl&gt;
 1 RUSSIAN CIVIL WAR I  RUS       1918
 2 COSTA RICAN COUP     NIC       1918
 3 COSTA RICAN COUP     COS       1918
 4 RUSSIAN CIVIL WAR II RUS       1918
 5 BALTIC INDEPENDENCE  RUS       1918
 6 BALTIC INDEPENDENCE  EST       1918
 7 BALTIC INDEPENDENCE  LIT       1918
 8 BALTIC INDEPENDENCE  LAT       1918
 9 TESCHEN              CZE       1919
10 TESCHEN              POL       1919
# ℹ 1,121 more rows</code></pre>
</div>
</div>
<p>An important thing to know about how R works: Just running a function like this won’t change your data frame permanently. To see this, after running <code>select()</code> like the above, go back and look at the data frame — nothing has changed:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>df_crises</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,131 × 95
   icb2  crisno cracno cracid actor systrgyr systrgmo systrgda crisname 
   &lt;chr&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;    
 1 ICB2       1      1    365 RUS       1918        5       NA RUSSIAN …
 2 ICB2       2      2     93 NIC       1918        5       25 COSTA RI…
 3 ICB2       2      3     94 COS       1918        5       25 COSTA RI…
 4 ICB2       3      4    365 RUS       1918        6       23 RUSSIAN …
 5 ICB2       4      5    365 RUS       1918       11       18 BALTIC I…
 6 ICB2       4      6    366 EST       1918       11       18 BALTIC I…
 7 ICB2       4      7    368 LIT       1918       11       18 BALTIC I…
 8 ICB2       4      8    367 LAT       1918       11       18 BALTIC I…
 9 ICB2       5      9    315 CZE       1919        1       15 TESCHEN  
10 ICB2       5     10    290 POL       1919        1       15 TESCHEN  
# ℹ 1,121 more rows
# ℹ 86 more variables: triggr &lt;dbl&gt;, yrtrig &lt;dbl&gt;, motrig &lt;dbl&gt;,
#   datrig &lt;dbl&gt;, trigent &lt;dbl&gt;, trigloc &lt;dbl&gt;, southv &lt;dbl&gt;,
#   southpow &lt;dbl&gt;, sizedu &lt;dbl&gt;, strcdu &lt;dbl&gt;, comlev &lt;dbl&gt;,
#   majres &lt;dbl&gt;, yerres &lt;dbl&gt;, monres &lt;dbl&gt;, dayres &lt;dbl&gt;,
#   trgresra &lt;dbl&gt;, crismg &lt;dbl&gt;, cenvio &lt;dbl&gt;, sevvio &lt;dbl&gt;,
#   usinv &lt;dbl&gt;, usfavr &lt;dbl&gt;, suinv &lt;dbl&gt;, sufavr &lt;dbl&gt;, …</code></pre>
</div>
</div>
<p>All the original data is still there. Unlike some other programming languages, R essentially never modifies data “in place”. If you want to overwrite <code>df_crises</code> with the subsetted version, you need to explicitly tell R to overwrite it by assigning the <code>select()</code>’ed data frame to <code>df_crises</code>, as in:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># I don't want to overwrite df_crises, so not actually running this</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>df_crises <span class="ot">&lt;-</span> <span class="fu">select</span>(df_crises, crisname, actor, systrgyr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Just as a matter of workflow, I usually try not to overwrite the raw data frame that I’ve read into R. That way, if I decide later on that I want more out of the original data, I don’t have to go back and load from the CSV file and clean it up again. So in this case, I would typically just create a new data frame with the subsetted data:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>df_crises_reduced <span class="ot">&lt;-</span> <span class="fu">select</span>(df_crises, crisname, actor, systrgyr)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>df_crises_reduced</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,131 × 3
   crisname             actor systrgyr
   &lt;chr&gt;                &lt;chr&gt;    &lt;dbl&gt;
 1 RUSSIAN CIVIL WAR I  RUS       1918
 2 COSTA RICAN COUP     NIC       1918
 3 COSTA RICAN COUP     COS       1918
 4 RUSSIAN CIVIL WAR II RUS       1918
 5 BALTIC INDEPENDENCE  RUS       1918
 6 BALTIC INDEPENDENCE  EST       1918
 7 BALTIC INDEPENDENCE  LIT       1918
 8 BALTIC INDEPENDENCE  LAT       1918
 9 TESCHEN              CZE       1919
10 TESCHEN              POL       1919
# ℹ 1,121 more rows</code></pre>
</div>
</div>
</section>
<section id="selecting-by-range-or-pattern" class="level4" data-number="2.2.1.2">
<h4 data-number="2.2.1.2" class="anchored" data-anchor-id="selecting-by-range-or-pattern"><span class="header-section-number">2.2.1.2</span> Selecting by range or pattern</h4>
<p>Suppose you wanted everything from the <code>crisno</code> column through the <code>systrgyr</code> column. Instead of typing out each column name explicitly, you can just use a colon (<code>:</code>) to tell <code>select()</code> to grab this range of variables:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(df_crises, crisno<span class="sc">:</span>systrgyr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,131 × 5
   crisno cracno cracid actor systrgyr
    &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;    &lt;dbl&gt;
 1      1      1    365 RUS       1918
 2      2      2     93 NIC       1918
 3      2      3     94 COS       1918
 4      3      4    365 RUS       1918
 5      4      5    365 RUS       1918
 6      4      6    366 EST       1918
 7      4      7    368 LIT       1918
 8      4      8    367 LAT       1918
 9      5      9    315 CZE       1919
10      5     10    290 POL       1919
# ℹ 1,121 more rows</code></pre>
</div>
</div>
<p>If you want everything <em>except</em> a particular variable, you can use the minus sign (<code>-</code>) to exclude it. Let’s see how to get rid of the useless <code>icb2</code> column that just marks the dataset version:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(df_crises, <span class="sc">-</span>icb2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,131 × 94
   crisno cracno cracid actor systrgyr systrgmo systrgda crisname triggr
    &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt;
 1      1      1    365 RUS       1918        5       NA RUSSIAN…      9
 2      2      2     93 NIC       1918        5       25 COSTA R…      7
 3      2      3     94 COS       1918        5       25 COSTA R…      4
 4      3      4    365 RUS       1918        6       23 RUSSIAN…      7
 5      4      5    365 RUS       1918       11       18 BALTIC …      6
 6      4      6    366 EST       1918       11       18 BALTIC …      9
 7      4      7    368 LIT       1918       11       18 BALTIC …      9
 8      4      8    367 LAT       1918       11       18 BALTIC …      9
 9      5      9    315 CZE       1919        1       15 TESCHEN       2
10      5     10    290 POL       1919        1       15 TESCHEN       7
# ℹ 1,121 more rows
# ℹ 85 more variables: yrtrig &lt;dbl&gt;, motrig &lt;dbl&gt;, datrig &lt;dbl&gt;,
#   trigent &lt;dbl&gt;, trigloc &lt;dbl&gt;, southv &lt;dbl&gt;, southpow &lt;dbl&gt;,
#   sizedu &lt;dbl&gt;, strcdu &lt;dbl&gt;, comlev &lt;dbl&gt;, majres &lt;dbl&gt;,
#   yerres &lt;dbl&gt;, monres &lt;dbl&gt;, dayres &lt;dbl&gt;, trgresra &lt;dbl&gt;,
#   crismg &lt;dbl&gt;, cenvio &lt;dbl&gt;, sevvio &lt;dbl&gt;, usinv &lt;dbl&gt;,
#   usfavr &lt;dbl&gt;, suinv &lt;dbl&gt;, sufavr &lt;dbl&gt;, gbinv &lt;dbl&gt;, …</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="In-class exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>In-class exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>What if you wanted to exclude the range of variables from <code>actor</code> through <code>yrtrig</code>? How would you do that without typing out each column name explicitly?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="co"># [Write your answer here]</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
<p>You can use the <code>starts_with()</code> subfunction to select all of the columns whose name starts with “sys”, for example:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(df_crises, <span class="fu">starts_with</span>(<span class="st">"sys"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,131 × 4
   systrgyr systrgmo systrgda syslev
      &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;
 1     1918        5       NA      2
 2     1918        5       25      1
 3     1918        5       25      1
 4     1918        6       23      2
 5     1918       11       18      2
 6     1918       11       18      1
 7     1918       11       18      1
 8     1918       11       18      1
 9     1919        1       15      1
10     1919        1       15      1
# ℹ 1,121 more rows</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="In-class exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>In-class exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>What happens if you instead run <code>select(df_crises, starts_with(sys))</code> (without the quotation marks around <code>sys</code>)? Why doesn’t this work?</p>
<blockquote class="blockquote">
<p>[Write your answer here]</p>
</blockquote>
</div>
</div>
<p>There are many other subfunctions you can use to select columns without naming them each explicitly. You can learn about them by looking at the <span class="concept">help page</span> for the <code>select()</code> function. To see the help page for any R function, just enter <code>?name_of_function</code> at the R console, like the following:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>?select</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="callout callout-style-default callout-note callout-titled" title="In-class exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>In-class exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Select the columns whose name has <code>"fav"</code> anywhere in it. Look at the <code>?select</code> help page to figure out the subfunction you need to do this.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="co"># [Write your answer here]</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</section>
<section id="reordering-and-renaming" class="level4" data-number="2.2.1.3">
<h4 data-number="2.2.1.3" class="anchored" data-anchor-id="reordering-and-renaming"><span class="header-section-number">2.2.1.3</span> Reordering and renaming</h4>
<p>As you select variables, you can rename them by using the syntax <code>newname = oldname</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(df_crises, <span class="at">year =</span> systrgyr, <span class="at">name =</span> crisname)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,131 × 2
    year name                
   &lt;dbl&gt; &lt;chr&gt;               
 1  1918 RUSSIAN CIVIL WAR I 
 2  1918 COSTA RICAN COUP    
 3  1918 COSTA RICAN COUP    
 4  1918 RUSSIAN CIVIL WAR II
 5  1918 BALTIC INDEPENDENCE 
 6  1918 BALTIC INDEPENDENCE 
 7  1918 BALTIC INDEPENDENCE 
 8  1918 BALTIC INDEPENDENCE 
 9  1919 TESCHEN             
10  1919 TESCHEN             
# ℹ 1,121 more rows</code></pre>
</div>
</div>
<p>To rename individual columns without dropping or rearranging the other columns, use the <code>rename()</code> function instead of <code>select()</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rename</span>(df_crises, <span class="at">year =</span> systrgyr, <span class="at">name =</span> crisname)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,131 × 95
   icb2  crisno cracno cracid actor  year systrgmo systrgda name  triggr
   &lt;chr&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;  &lt;dbl&gt;
 1 ICB2       1      1    365 RUS    1918        5       NA RUSS…      9
 2 ICB2       2      2     93 NIC    1918        5       25 COST…      7
 3 ICB2       2      3     94 COS    1918        5       25 COST…      4
 4 ICB2       3      4    365 RUS    1918        6       23 RUSS…      7
 5 ICB2       4      5    365 RUS    1918       11       18 BALT…      6
 6 ICB2       4      6    366 EST    1918       11       18 BALT…      9
 7 ICB2       4      7    368 LIT    1918       11       18 BALT…      9
 8 ICB2       4      8    367 LAT    1918       11       18 BALT…      9
 9 ICB2       5      9    315 CZE    1919        1       15 TESC…      2
10 ICB2       5     10    290 POL    1919        1       15 TESC…      7
# ℹ 1,121 more rows
# ℹ 85 more variables: yrtrig &lt;dbl&gt;, motrig &lt;dbl&gt;, datrig &lt;dbl&gt;,
#   trigent &lt;dbl&gt;, trigloc &lt;dbl&gt;, southv &lt;dbl&gt;, southpow &lt;dbl&gt;,
#   sizedu &lt;dbl&gt;, strcdu &lt;dbl&gt;, comlev &lt;dbl&gt;, majres &lt;dbl&gt;,
#   yerres &lt;dbl&gt;, monres &lt;dbl&gt;, dayres &lt;dbl&gt;, trgresra &lt;dbl&gt;,
#   crismg &lt;dbl&gt;, cenvio &lt;dbl&gt;, sevvio &lt;dbl&gt;, usinv &lt;dbl&gt;,
#   usfavr &lt;dbl&gt;, suinv &lt;dbl&gt;, sufavr &lt;dbl&gt;, gbinv &lt;dbl&gt;, …</code></pre>
</div>
</div>
<p>If you want certain columns to be placed first, use the <code>relocate()</code> function.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">relocate</span>(df_crises, crisname, actor)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,131 × 95
   crisname  actor icb2  crisno cracno cracid systrgyr systrgmo systrgda
   &lt;chr&gt;     &lt;chr&gt; &lt;chr&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
 1 RUSSIAN … RUS   ICB2       1      1    365     1918        5       NA
 2 COSTA RI… NIC   ICB2       2      2     93     1918        5       25
 3 COSTA RI… COS   ICB2       2      3     94     1918        5       25
 4 RUSSIAN … RUS   ICB2       3      4    365     1918        6       23
 5 BALTIC I… RUS   ICB2       4      5    365     1918       11       18
 6 BALTIC I… EST   ICB2       4      6    366     1918       11       18
 7 BALTIC I… LIT   ICB2       4      7    368     1918       11       18
 8 BALTIC I… LAT   ICB2       4      8    367     1918       11       18
 9 TESCHEN   CZE   ICB2       5      9    315     1919        1       15
10 TESCHEN   POL   ICB2       5     10    290     1919        1       15
# ℹ 1,121 more rows
# ℹ 86 more variables: triggr &lt;dbl&gt;, yrtrig &lt;dbl&gt;, motrig &lt;dbl&gt;,
#   datrig &lt;dbl&gt;, trigent &lt;dbl&gt;, trigloc &lt;dbl&gt;, southv &lt;dbl&gt;,
#   southpow &lt;dbl&gt;, sizedu &lt;dbl&gt;, strcdu &lt;dbl&gt;, comlev &lt;dbl&gt;,
#   majres &lt;dbl&gt;, yerres &lt;dbl&gt;, monres &lt;dbl&gt;, dayres &lt;dbl&gt;,
#   trgresra &lt;dbl&gt;, crismg &lt;dbl&gt;, cenvio &lt;dbl&gt;, sevvio &lt;dbl&gt;,
#   usinv &lt;dbl&gt;, usfavr &lt;dbl&gt;, suinv &lt;dbl&gt;, sufavr &lt;dbl&gt;, …</code></pre>
</div>
</div>
<p>To rearrange the rows of the data, you can use the <code>arrange()</code> function. By default, it sorts the data in ascending order of the column name(s) you feed it.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Arrange in ascending order of actor numeric ID</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">arrange</span>(df_crises, cracid)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,131 × 95
   icb2  crisno cracno cracid actor systrgyr systrgmo systrgda crisname 
   &lt;chr&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;    
 1 ICB2      59    128      2 USA       1937       12       12 PANAY IN…
 2 ICB2      88    224      2 USA       1941       11       26 PEARL HA…
 3 ICB2     104    251      2 USA       1945        5        1 TRIESTE I
 4 ICB2     108    259      2 USA       1945        8       23 AZERBAIJ…
 5 ICB2     111    265      2 USA       1946        8        7 TURKISH …
 6 ICB2     114    271      2 USA       1947        2       21 TRUMAN D…
 7 ICB2     123    293      2 USA       1948        6        7 BERLIN B…
 8 ICB2     125    295      2 USA       1948        9       23 CHINA CI…
 9 ICB2     132    308      2 USA       1950        6       25 KOREAN W…
10 ICB2     133    314      2 USA       1950        9       30 KOREAN W…
# ℹ 1,121 more rows
# ℹ 86 more variables: triggr &lt;dbl&gt;, yrtrig &lt;dbl&gt;, motrig &lt;dbl&gt;,
#   datrig &lt;dbl&gt;, trigent &lt;dbl&gt;, trigloc &lt;dbl&gt;, southv &lt;dbl&gt;,
#   southpow &lt;dbl&gt;, sizedu &lt;dbl&gt;, strcdu &lt;dbl&gt;, comlev &lt;dbl&gt;,
#   majres &lt;dbl&gt;, yerres &lt;dbl&gt;, monres &lt;dbl&gt;, dayres &lt;dbl&gt;,
#   trgresra &lt;dbl&gt;, crismg &lt;dbl&gt;, cenvio &lt;dbl&gt;, sevvio &lt;dbl&gt;,
#   usinv &lt;dbl&gt;, usfavr &lt;dbl&gt;, suinv &lt;dbl&gt;, sufavr &lt;dbl&gt;, …</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Arrange by start year, then by actor ID within year</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">arrange</span>(df_crises, systrgyr, cracid)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,131 × 95
   icb2  crisno cracno cracid actor systrgyr systrgmo systrgda crisname 
   &lt;chr&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;    
 1 ICB2       2      2     93 NIC       1918        5       25 COSTA RI…
 2 ICB2       2      3     94 COS       1918        5       25 COSTA RI…
 3 ICB2       1      1    365 RUS       1918        5       NA RUSSIAN …
 4 ICB2       3      4    365 RUS       1918        6       23 RUSSIAN …
 5 ICB2       4      5    365 RUS       1918       11       18 BALTIC I…
 6 ICB2       4      6    366 EST       1918       11       18 BALTIC I…
 7 ICB2       4      8    367 LAT       1918       11       18 BALTIC I…
 8 ICB2       4      7    368 LIT       1918       11       18 BALTIC I…
 9 ICB2       8     18    200 UKG       1919        4       15 THIRD AF…
10 ICB2      11     24    220 FRN       1919       11       NA CILICIAN…
# ℹ 1,121 more rows
# ℹ 86 more variables: triggr &lt;dbl&gt;, yrtrig &lt;dbl&gt;, motrig &lt;dbl&gt;,
#   datrig &lt;dbl&gt;, trigent &lt;dbl&gt;, trigloc &lt;dbl&gt;, southv &lt;dbl&gt;,
#   southpow &lt;dbl&gt;, sizedu &lt;dbl&gt;, strcdu &lt;dbl&gt;, comlev &lt;dbl&gt;,
#   majres &lt;dbl&gt;, yerres &lt;dbl&gt;, monres &lt;dbl&gt;, dayres &lt;dbl&gt;,
#   trgresra &lt;dbl&gt;, crismg &lt;dbl&gt;, cenvio &lt;dbl&gt;, sevvio &lt;dbl&gt;,
#   usinv &lt;dbl&gt;, usfavr &lt;dbl&gt;, suinv &lt;dbl&gt;, sufavr &lt;dbl&gt;, …</code></pre>
</div>
</div>
<p>To instead sort in descending order, wrap the variable name in <code>desc()</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Arrange so that the most recent crises come first</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">arrange</span>(df_crises, <span class="fu">desc</span>(systrgyr))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,131 × 95
   icb2  crisno cracno cracid actor systrgyr systrgmo systrgda crisname 
   &lt;chr&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;    
 1 ICB2     506   1117    615 ALG       2021        1        9 US VISIT…
 2 ICB2     507   1118    710 CHN       2021        1        9 US-TAIWA…
 3 ICB2     507   1119    713 TAW       2021        1        9 US-TAIWA…
 4 ICB2     508   1120    652 SYR       2021        1       13 ISRAEL-I…
 5 ICB2     508   1121    630 IRN       2021        1       13 ISRAEL-I…
 6 ICB2     509   1122    740 JPN       2021        1       22 CHINA CO…
 7 ICB2     511   1128    703 KYR       2021        4       28 KOK-TASH…
 8 ICB2     511   1129    702 TAJ       2021        4       28 KOK-TASH…
 9 ICB2     512   1130    345 YUG       2021        9       20 KOSOVO L…
10 ICB2     512   1131    347 KOS       2021        9       20 KOSOVO L…
# ℹ 1,121 more rows
# ℹ 86 more variables: triggr &lt;dbl&gt;, yrtrig &lt;dbl&gt;, motrig &lt;dbl&gt;,
#   datrig &lt;dbl&gt;, trigent &lt;dbl&gt;, trigloc &lt;dbl&gt;, southv &lt;dbl&gt;,
#   southpow &lt;dbl&gt;, sizedu &lt;dbl&gt;, strcdu &lt;dbl&gt;, comlev &lt;dbl&gt;,
#   majres &lt;dbl&gt;, yerres &lt;dbl&gt;, monres &lt;dbl&gt;, dayres &lt;dbl&gt;,
#   trgresra &lt;dbl&gt;, crismg &lt;dbl&gt;, cenvio &lt;dbl&gt;, sevvio &lt;dbl&gt;,
#   usinv &lt;dbl&gt;, usfavr &lt;dbl&gt;, suinv &lt;dbl&gt;, sufavr &lt;dbl&gt;, …</code></pre>
</div>
</div>
</section>
</section>
<section id="subsetting-by-row-filter" class="level3 page-columns page-full" data-number="2.2.2">
<h3 data-number="2.2.2" class="anchored" data-anchor-id="subsetting-by-row-filter"><span class="header-section-number">2.2.2</span> Subsetting by row: <code>filter()</code></h3>
<p>What if we only want the crises that started during the Cold War? That involves selecting rows from the data rather than columns, which we’ll use the <code>filter()</code> function for. But before we can do that, we need to learn a bit about making logical statements in R.</p>
<section id="comparisons-and-logical-operators" class="level4 page-columns page-full" data-number="2.2.2.1">
<h4 data-number="2.2.2.1" class="anchored" data-anchor-id="comparisons-and-logical-operators"><span class="header-section-number">2.2.2.1</span> Comparisons and logical operators</h4>
<p>If we make a <strong>comparison</strong> in R, it will spit out whether our statement is <code>TRUE</code> or <code>FALSE</code>. There are six logical comparisons we can make in R:</p>
<ul>
<li><p><code>x == y</code>: Is <code>x</code> equal to <code>y</code>? (Notice that we use a double equals sign, not a single one!)</p></li>
<li><p><code>x != y</code>: Is <code>x</code> unequal to <code>y</code>?</p></li>
<li><p><code>x &gt; y</code>: Is <code>x</code> greater than <code>y</code>?</p></li>
<li><p><code>x &gt;= y</code>: Is <code>x</code> greater than or equal to <code>y</code>?</p></li>
<li><p><code>x &lt; y</code>: Is <code>x</code> less than <code>y</code>?</p></li>
<li><p><code>x &lt;= y</code>: Is <code>x</code> less than or equal to <code>y</code>?</p></li>
</ul>
<p>As an example, let’s assign the value 1950 to the variable <code>x</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">1950</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Now let’s look at the values of a few logical comparisons.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>x <span class="sc">==</span> <span class="dv">1950</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>x <span class="sc">==</span> <span class="dv">1951</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>x <span class="sc">!=</span> <span class="dv">1951</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>x <span class="sc">&lt;</span> <span class="dv">1950</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>x <span class="sc">&lt;=</span> <span class="dv">1950</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<p>If we use these with a vector of numbers, R calculates the comparison for each individual element of the vector. So instead of just looking at 1950, let’s look at each number from 1948 to 1952.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">1948</span><span class="sc">:</span><span class="dv">1952</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>x</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1948 1949 1950 1951 1952</code></pre>
</div>
</div>
<p>We’ve got a vector of five years here, so each of our logical comparisons will now return a vector of five <code>TRUE</code>/<code>FALSE</code> values.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>x <span class="sc">==</span> <span class="dv">1950</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE FALSE  TRUE FALSE FALSE</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>x <span class="sc">==</span> <span class="dv">1951</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE FALSE FALSE  TRUE FALSE</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>x <span class="sc">!=</span> <span class="dv">1951</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  TRUE  TRUE  TRUE FALSE  TRUE</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>x <span class="sc">&lt;</span> <span class="dv">1950</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  TRUE  TRUE FALSE FALSE FALSE</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>x <span class="sc">&lt;=</span> <span class="dv">1950</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  TRUE  TRUE  TRUE FALSE FALSE</code></pre>
</div>
</div>
<p>You can combine logical comparisons like this with square brackets to select elements from a vector on the basis of a logical comparison.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>x[x <span class="sc">&lt;</span> <span class="dv">1950</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1948 1949</code></pre>
</div>
</div>
<p>Above we’ve compared a vector to a single number. What if we compare a vector to another vector of the same length?</p>

<div class="no-row-height column-margin column-container"><div class="margin-aside">
<p>The last possibility is comparing a vector to another vector of a <em>different</em> length. Loosely speaking, R handles this situation by repeating the shorter vector until the two match up. R’s behavior in this situation can be hard to predict, so I recommend only doing logical comparisons against either a single number, or a vector of the same length. You can check the length of a vector using the <code>length()</code> function, FYI.</p>
</div></div><div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1948</span>, <span class="dv">1948</span>, <span class="dv">1950</span>, <span class="dv">1950</span>, <span class="dv">1946</span>)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>y</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1948 1948 1950 1950 1946</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>x <span class="sc">==</span> y</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  TRUE FALSE  TRUE FALSE FALSE</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>x <span class="sc">!=</span> y</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE  TRUE FALSE  TRUE  TRUE</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>x <span class="sc">&gt;</span> y</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE  TRUE FALSE  TRUE  TRUE</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>x <span class="sc">&gt;=</span> y</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE TRUE TRUE TRUE TRUE</code></pre>
</div>
</div>
<p>The exclamation point means “not”. You can use it to turn <code>TRUE</code> into <code>FALSE</code> and vice versa. Just make sure that you put parentheses around the whole statement that you’re trying to negate.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="sc">!</span>(x <span class="sc">&gt;=</span> y)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE FALSE FALSE FALSE FALSE</code></pre>
</div>
</div>
<p>Sometimes we will want to string together multiple comparisons. There are two ways to combine comparisons.</p>
<ul>
<li><p><span class="concept">and</span>: <code>a &amp; b</code> is <code>TRUE</code> when <code>a</code> is <code>TRUE</code> and <code>b</code> is also <code>TRUE</code>. If either or both are <code>FALSE</code>, then so is <code>a &amp; b</code>.</p></li>
<li><p><span class="concept">or</span>: <code>a | b</code> is <code>TRUE</code> when <code>a</code> is <code>TRUE</code>, or <code>b</code> is <code>TRUE</code>, or both. The only way for <code>a | b</code> to be <code>FALSE</code> is for both <code>a</code> and <code>b</code> to be FALSE.</p></li>
</ul>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;"><code>a</code></th>
<th style="text-align: left;"><code>b</code></th>
<th style="text-align: left;"><code>a &amp; b</code> (and)</th>
<th style="text-align: left;"><code>a | b</code> (or)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>TRUE</code></td>
<td style="text-align: left;"><code>TRUE</code></td>
<td style="text-align: left;"><code>TRUE</code></td>
<td style="text-align: left;"><code>TRUE</code></td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>TRUE</code></td>
<td style="text-align: left;"><code>FALSE</code></td>
<td style="text-align: left;"><code>FALSE</code></td>
<td style="text-align: left;"><code>TRUE</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>FALSE</code></td>
<td style="text-align: left;"><code>TRUE</code></td>
<td style="text-align: left;"><code>FALSE</code></td>
<td style="text-align: left;"><code>TRUE</code></td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>FALSE</code></td>
<td style="text-align: left;"><code>FALSE</code></td>
<td style="text-align: left;"><code>FALSE</code></td>
<td style="text-align: left;"><code>FALSE</code></td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reminder:</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a><span class="co"># x = 1948, 1949, 1950, 1951, 1952</span></span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a><span class="co"># y = 1948, 1948, 1950, 1950, 1946</span></span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a>x <span class="sc">&gt;</span> y <span class="sc">&amp;</span> x <span class="sc">&lt;</span> <span class="dv">1950</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE  TRUE FALSE FALSE FALSE</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>x <span class="sc">&gt;</span> y <span class="sc">|</span> x <span class="sc">&lt;</span> <span class="dv">1950</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  TRUE  TRUE FALSE  TRUE  TRUE</code></pre>
</div>
</div>
<p>Be aware that <code>&amp;</code> and <code>|</code> only operate on <code>TRUE</code> and <code>FALSE</code> values, not on other values. There are situations where you might use “and” or “or” in an English sentence, but where <code>&amp;</code> and <code>|</code> can’t just be substituted into your R code. For example, think about trying to code up the logical statement “<code>x</code> or <code>y</code> is less than 100.”</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">75</span>, <span class="dv">100</span>, <span class="dv">125</span>, <span class="dv">150</span>)</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">100</span>, <span class="dv">90</span>, <span class="dv">150</span>, <span class="dv">99</span>)</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Won't work correctly, because x and y aren't TRUE/FALSE</span></span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>(x <span class="sc">|</span> y) <span class="sc">&lt;</span> <span class="dv">100</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE TRUE TRUE TRUE</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Will work correctly, because "x &lt; 100" and "y &lt; 100" are TRUE/FALSE</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>(x <span class="sc">&lt;</span> <span class="dv">100</span>) <span class="sc">|</span> (y <span class="sc">&lt;</span> <span class="dv">100</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  TRUE  TRUE FALSE  TRUE</code></pre>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="margin-aside">
<p>Completely optional aside for those who are morbidly curious why we get all <code>TRUE</code> values when we run <code>(x | y) &lt; 100</code>: When you plug numbers into a logical operator, any non-zero number evaluates to <code>TRUE</code>. Since every element of <code>x</code> and <code>y</code> is nonzero, <code>x | y</code> evaluates to <code>TRUE, TRUE, TRUE, TRUE</code>. Then, when you plug logical values into a numerical comparison, <code>TRUE</code> values are treated like 1 and <code>FALSE</code> values like 0. So R converts each <code>TRUE</code> to 1, observes that 1 is less than 100, and again returns <code>TRUE</code> for each one.</p>
</div></div><p>One final minor note: If you look for R help on the Internet, you’ll sometimes see people use <code>&amp;&amp;</code> and <code>||</code>. What’s the difference between <code>&amp;</code> and <code>&amp;&amp;</code>, or between <code>|</code> and <code>||</code>? The doubled versions only work on a <u>single</u> <code>TRUE</code>/<code>FALSE</code> statement. This distinction is important in programming situations where you need to make sure you’re only working with a single value. That won’t typically come up in this course, so to make our lives easier we’ll just always use the single versions.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>)</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">8</span>)</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>x <span class="sc">&lt;</span> y <span class="sc">|</span> x <span class="sc">&gt;</span> y   <span class="co"># returns c(FALSE, TRUE, TRUE, FALSE, TRUE)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE  TRUE  TRUE FALSE  TRUE</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>x <span class="sc">&lt;</span> y <span class="sc">||</span> x <span class="sc">&gt;</span> y  <span class="co"># won't run, will give error message</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-error">
<pre><code>Error in x &lt; y || x &gt; y: 'length = 5' in coercion to 'logical(1)'</code></pre>
</div>
</div>
</section>
<section id="the-filter-function" class="level4" data-number="2.2.2.2">
<h4 data-number="2.2.2.2" class="anchored" data-anchor-id="the-filter-function"><span class="header-section-number">2.2.2.2</span> The <code>filter()</code> function</h4>
<p>Now that we’re familiar with comparisons and logical operators, let’s return to the crisis data to reduce it down to Cold War–era observations.</p>
<p>Remember that we can pull a single column from a data frame using the dollar sign. And we can use square brackets on a data frame to select particular observations from it. So we <em>could</em> subset to the Cold War observations that way.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>df_crises[df_crises<span class="sc">$</span>systrgyr <span class="sc">&gt;=</span> <span class="dv">1946</span> <span class="sc">&amp;</span> df_crises<span class="sc">$</span>systrgyr <span class="sc">&lt;=</span> <span class="dv">1989</span>, ]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 585 × 95
   icb2  crisno cracno cracid actor systrgyr systrgmo systrgda crisname 
   &lt;chr&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;    
 1 ICB2     110    263    365 RUS       1946        6       30 COMMUNIS…
 2 ICB2     111    264    640 TUR       1946        8        7 TURKISH …
 3 ICB2     111    265      2 USA       1946        8        7 TURKISH …
 4 ICB2     112    266    350 GRC       1946       11       13 GREEK CI…
 5 ICB2     113    267    365 RUS       1947        2       10 COMMUNIS…
 6 ICB2     113    268    310 HUN       1947        2       10 COMMUNIS…
 7 ICB2     114    269    350 GRC       1947        2       21 TRUMAN D…
 8 ICB2     114    270    640 TUR       1947        2       21 TRUMAN D…
 9 ICB2     114    271      2 USA       1947        2       21 TRUMAN D…
10 ICB2     115    272    365 RUS       1947        7        3 MARSHALL…
# ℹ 575 more rows
# ℹ 86 more variables: triggr &lt;dbl&gt;, yrtrig &lt;dbl&gt;, motrig &lt;dbl&gt;,
#   datrig &lt;dbl&gt;, trigent &lt;dbl&gt;, trigloc &lt;dbl&gt;, southv &lt;dbl&gt;,
#   southpow &lt;dbl&gt;, sizedu &lt;dbl&gt;, strcdu &lt;dbl&gt;, comlev &lt;dbl&gt;,
#   majres &lt;dbl&gt;, yerres &lt;dbl&gt;, monres &lt;dbl&gt;, dayres &lt;dbl&gt;,
#   trgresra &lt;dbl&gt;, crismg &lt;dbl&gt;, cenvio &lt;dbl&gt;, sevvio &lt;dbl&gt;,
#   usinv &lt;dbl&gt;, usfavr &lt;dbl&gt;, suinv &lt;dbl&gt;, sufavr &lt;dbl&gt;, …</code></pre>
</div>
</div>
<p>That works, but it’s a bit ugly and unwieldy. The <code>filter()</code> function gives us an easier way to do the same thing.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(df_crises, systrgyr <span class="sc">&gt;=</span> <span class="dv">1946</span> <span class="sc">&amp;</span> systrgyr <span class="sc">&lt;=</span> <span class="dv">1989</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 580 × 95
   icb2  crisno cracno cracid actor systrgyr systrgmo systrgda crisname 
   &lt;chr&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;    
 1 ICB2     110    263    365 RUS       1946        6       30 COMMUNIS…
 2 ICB2     111    264    640 TUR       1946        8        7 TURKISH …
 3 ICB2     111    265      2 USA       1946        8        7 TURKISH …
 4 ICB2     112    266    350 GRC       1946       11       13 GREEK CI…
 5 ICB2     113    267    365 RUS       1947        2       10 COMMUNIS…
 6 ICB2     113    268    310 HUN       1947        2       10 COMMUNIS…
 7 ICB2     114    269    350 GRC       1947        2       21 TRUMAN D…
 8 ICB2     114    270    640 TUR       1947        2       21 TRUMAN D…
 9 ICB2     114    271      2 USA       1947        2       21 TRUMAN D…
10 ICB2     115    272    365 RUS       1947        7        3 MARSHALL…
# ℹ 570 more rows
# ℹ 86 more variables: triggr &lt;dbl&gt;, yrtrig &lt;dbl&gt;, motrig &lt;dbl&gt;,
#   datrig &lt;dbl&gt;, trigent &lt;dbl&gt;, trigloc &lt;dbl&gt;, southv &lt;dbl&gt;,
#   southpow &lt;dbl&gt;, sizedu &lt;dbl&gt;, strcdu &lt;dbl&gt;, comlev &lt;dbl&gt;,
#   majres &lt;dbl&gt;, yerres &lt;dbl&gt;, monres &lt;dbl&gt;, dayres &lt;dbl&gt;,
#   trgresra &lt;dbl&gt;, crismg &lt;dbl&gt;, cenvio &lt;dbl&gt;, sevvio &lt;dbl&gt;,
#   usinv &lt;dbl&gt;, usfavr &lt;dbl&gt;, suinv &lt;dbl&gt;, sufavr &lt;dbl&gt;, …</code></pre>
</div>
</div>
<p>When dealing with character columns, the greater/lesser comparisons no longer make sense, but we can still use the equality and inequality comparisons. Just make sure to use quotation marks around whatever you’re comparing to!</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(df_crises, actor <span class="sc">==</span> <span class="st">"USA"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 78 × 95
   icb2  crisno cracno cracid actor systrgyr systrgmo systrgda crisname 
   &lt;chr&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;    
 1 ICB2      59    128      2 USA       1937       12       12 PANAY IN…
 2 ICB2      88    224      2 USA       1941       11       26 PEARL HA…
 3 ICB2     104    251      2 USA       1945        5        1 TRIESTE I
 4 ICB2     108    259      2 USA       1945        8       23 AZERBAIJ…
 5 ICB2     111    265      2 USA       1946        8        7 TURKISH …
 6 ICB2     114    271      2 USA       1947        2       21 TRUMAN D…
 7 ICB2     123    293      2 USA       1948        6        7 BERLIN B…
 8 ICB2     125    295      2 USA       1948        9       23 CHINA CI…
 9 ICB2     132    308      2 USA       1950        6       25 KOREAN W…
10 ICB2     133    314      2 USA       1950        9       30 KOREAN W…
# ℹ 68 more rows
# ℹ 86 more variables: triggr &lt;dbl&gt;, yrtrig &lt;dbl&gt;, motrig &lt;dbl&gt;,
#   datrig &lt;dbl&gt;, trigent &lt;dbl&gt;, trigloc &lt;dbl&gt;, southv &lt;dbl&gt;,
#   southpow &lt;dbl&gt;, sizedu &lt;dbl&gt;, strcdu &lt;dbl&gt;, comlev &lt;dbl&gt;,
#   majres &lt;dbl&gt;, yerres &lt;dbl&gt;, monres &lt;dbl&gt;, dayres &lt;dbl&gt;,
#   trgresra &lt;dbl&gt;, crismg &lt;dbl&gt;, cenvio &lt;dbl&gt;, sevvio &lt;dbl&gt;,
#   usinv &lt;dbl&gt;, usfavr &lt;dbl&gt;, suinv &lt;dbl&gt;, sufavr &lt;dbl&gt;, …</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(df_crises, actor <span class="sc">!=</span> <span class="st">"RUS"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,079 × 95
   icb2  crisno cracno cracid actor systrgyr systrgmo systrgda crisname 
   &lt;chr&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;    
 1 ICB2       2      2     93 NIC       1918        5       25 COSTA RI…
 2 ICB2       2      3     94 COS       1918        5       25 COSTA RI…
 3 ICB2       4      6    366 EST       1918       11       18 BALTIC I…
 4 ICB2       4      7    368 LIT       1918       11       18 BALTIC I…
 5 ICB2       4      8    367 LAT       1918       11       18 BALTIC I…
 6 ICB2       5      9    315 CZE       1919        1       15 TESCHEN  
 7 ICB2       5     10    290 POL       1919        1       15 TESCHEN  
 8 ICB2       6     11    310 HUN       1919        3       20 HUNGARIA…
 9 ICB2       6     12    315 CZE       1919        3       20 HUNGARIA…
10 ICB2       6     13    310 HUN       1919        3       20 HUNGARIA…
# ℹ 1,069 more rows
# ℹ 86 more variables: triggr &lt;dbl&gt;, yrtrig &lt;dbl&gt;, motrig &lt;dbl&gt;,
#   datrig &lt;dbl&gt;, trigent &lt;dbl&gt;, trigloc &lt;dbl&gt;, southv &lt;dbl&gt;,
#   southpow &lt;dbl&gt;, sizedu &lt;dbl&gt;, strcdu &lt;dbl&gt;, comlev &lt;dbl&gt;,
#   majres &lt;dbl&gt;, yerres &lt;dbl&gt;, monres &lt;dbl&gt;, dayres &lt;dbl&gt;,
#   trgresra &lt;dbl&gt;, crismg &lt;dbl&gt;, cenvio &lt;dbl&gt;, sevvio &lt;dbl&gt;,
#   usinv &lt;dbl&gt;, usfavr &lt;dbl&gt;, suinv &lt;dbl&gt;, sufavr &lt;dbl&gt;, …</code></pre>
</div>
</div>
<p>What if you wanted to get all of the observations involving the United States (USA), Russia (RUS), or the United Kingdom (UKG)? One kind of tedious way to go about it would be to string many “or” statements together.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(df_crises, actor <span class="sc">==</span> <span class="st">"USA"</span> <span class="sc">|</span> actor <span class="sc">==</span> <span class="st">"RUS"</span> <span class="sc">|</span> actor <span class="sc">==</span> <span class="st">"UKG"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 178 × 95
   icb2  crisno cracno cracid actor systrgyr systrgmo systrgda crisname 
   &lt;chr&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;    
 1 ICB2       1      1    365 RUS       1918        5       NA RUSSIAN …
 2 ICB2       3      4    365 RUS       1918        6       23 RUSSIAN …
 3 ICB2       4      5    365 RUS       1918       11       18 BALTIC I…
 4 ICB2       8     18    200 UKG       1919        4       15 THIRD AF…
 5 ICB2       9     19    365 RUS       1919        4       20 FINNISH/…
 6 ICB2      10     21    365 RUS       1919        4       30 BESSARAB…
 7 ICB2      13     27    365 RUS       1920        4       25 POLISH/R…
 8 ICB2      14     29    365 RUS       1920        5       66 PERSIAN …
 9 ICB2      26     56    200 UKG       1922        9       23 CHANAK   
10 ICB2      31     66    200 UKG       1924        9       29 MOSUL LA…
# ℹ 168 more rows
# ℹ 86 more variables: triggr &lt;dbl&gt;, yrtrig &lt;dbl&gt;, motrig &lt;dbl&gt;,
#   datrig &lt;dbl&gt;, trigent &lt;dbl&gt;, trigloc &lt;dbl&gt;, southv &lt;dbl&gt;,
#   southpow &lt;dbl&gt;, sizedu &lt;dbl&gt;, strcdu &lt;dbl&gt;, comlev &lt;dbl&gt;,
#   majres &lt;dbl&gt;, yerres &lt;dbl&gt;, monres &lt;dbl&gt;, dayres &lt;dbl&gt;,
#   trgresra &lt;dbl&gt;, crismg &lt;dbl&gt;, cenvio &lt;dbl&gt;, sevvio &lt;dbl&gt;,
#   usinv &lt;dbl&gt;, usfavr &lt;dbl&gt;, suinv &lt;dbl&gt;, sufavr &lt;dbl&gt;, …</code></pre>
</div>
</div>
<p>The easier way — especially if you’re matching a large number of values — is to use the <code>%in%</code> operator in R. When you run <code>x %in% y</code>, it gives you a <code>TRUE</code> or <code>FALSE</code> for each entry of <code>x</code>: <code>TRUE</code> if it matches at least one entry of <code>y</code>, and <code>FALSE</code> otherwise.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(df_crises, actor <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"USA"</span>, <span class="st">"RUS"</span>, <span class="st">"UKG"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 178 × 95
   icb2  crisno cracno cracid actor systrgyr systrgmo systrgda crisname 
   &lt;chr&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;    
 1 ICB2       1      1    365 RUS       1918        5       NA RUSSIAN …
 2 ICB2       3      4    365 RUS       1918        6       23 RUSSIAN …
 3 ICB2       4      5    365 RUS       1918       11       18 BALTIC I…
 4 ICB2       8     18    200 UKG       1919        4       15 THIRD AF…
 5 ICB2       9     19    365 RUS       1919        4       20 FINNISH/…
 6 ICB2      10     21    365 RUS       1919        4       30 BESSARAB…
 7 ICB2      13     27    365 RUS       1920        4       25 POLISH/R…
 8 ICB2      14     29    365 RUS       1920        5       66 PERSIAN …
 9 ICB2      26     56    200 UKG       1922        9       23 CHANAK   
10 ICB2      31     66    200 UKG       1924        9       29 MOSUL LA…
# ℹ 168 more rows
# ℹ 86 more variables: triggr &lt;dbl&gt;, yrtrig &lt;dbl&gt;, motrig &lt;dbl&gt;,
#   datrig &lt;dbl&gt;, trigent &lt;dbl&gt;, trigloc &lt;dbl&gt;, southv &lt;dbl&gt;,
#   southpow &lt;dbl&gt;, sizedu &lt;dbl&gt;, strcdu &lt;dbl&gt;, comlev &lt;dbl&gt;,
#   majres &lt;dbl&gt;, yerres &lt;dbl&gt;, monres &lt;dbl&gt;, dayres &lt;dbl&gt;,
#   trgresra &lt;dbl&gt;, crismg &lt;dbl&gt;, cenvio &lt;dbl&gt;, sevvio &lt;dbl&gt;,
#   usinv &lt;dbl&gt;, usfavr &lt;dbl&gt;, suinv &lt;dbl&gt;, sufavr &lt;dbl&gt;, …</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="In-class exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>In-class exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>How can you filter down to the observations that are <em>not</em> those three countries?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a><span class="co"># [Write your answer here]</span></span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</section>
</section>
<section id="piping-commands-together" class="level3" data-number="2.2.3">
<h3 data-number="2.2.3" class="anchored" data-anchor-id="piping-commands-together"><span class="header-section-number">2.2.3</span> “Piping” commands together</h3>
<p>Here’s a pretty common way to start off your data analysis workflow:</p>
<ol type="1">
<li>Load your raw data into R.</li>
<li>Reduce the columns down to the ones you will use in your analysis.</li>
<li>Filter out the rows that aren’t relevant to your analysis.</li>
</ol>
<p>Remember that R doesn’t save what you do to a data frame unless you explicitly assign the result to a variable. This means that a data cleaning process might involve a lot of intermediate assignments that you never end up using again.</p>
<p>Imagine we want to extract the name of the crisis, the name and numeric ID of the country involved, the year the crisis began, the number of days it lasted (<code>trgterra</code>), and the outcome for the given actor (<code>outcom</code>) Along the way we’ll rename the variables to be less ugly. And furthermore imagine we only want Cold War–era observations, and only for the USA, Russia, and the United Kingdom. We could run the following sequence of commands:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>df_crises_cw <span class="ot">&lt;-</span> <span class="fu">select</span>(</span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>  df_crises,</span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">crisis_name =</span> crisname,</span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">actor_name =</span> actor,</span>
<span id="cb93-5"><a href="#cb93-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">actor_id =</span> cracid,</span>
<span id="cb93-6"><a href="#cb93-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">year =</span> systrgyr,</span>
<span id="cb93-7"><a href="#cb93-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">duration =</span> trgterra,</span>
<span id="cb93-8"><a href="#cb93-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">outcome =</span> outcom</span>
<span id="cb93-9"><a href="#cb93-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb93-10"><a href="#cb93-10" aria-hidden="true" tabindex="-1"></a>df_crises_cw <span class="ot">&lt;-</span> <span class="fu">filter</span>(df_crises_cw, year <span class="sc">&gt;=</span> <span class="dv">1946</span> <span class="sc">&amp;</span> year <span class="sc">&lt;=</span> <span class="dv">1989</span>)</span>
<span id="cb93-11"><a href="#cb93-11" aria-hidden="true" tabindex="-1"></a>df_crises_cw <span class="ot">&lt;-</span> <span class="fu">filter</span>(df_crises_cw, actor_name <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"USA"</span>, <span class="st">"RUS"</span>, <span class="st">"UKG"</span>))</span>
<span id="cb93-12"><a href="#cb93-12" aria-hidden="true" tabindex="-1"></a>df_crises_cw</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 87 × 6
   crisis_name          actor_name actor_id  year duration outcome
   &lt;chr&gt;                &lt;chr&gt;         &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;
 1 COMMUNISM IN POLAND  RUS             365  1946      204       1
 2 TURKISH STRAITS      USA               2  1946       81       1
 3 COMMUNISM IN HUNGARY RUS             365  1947      112       1
 4 TRUMAN DOCTRINE      USA               2  1947       91       1
 5 MARSHALL PLAN        RUS             365  1947        9       1
 6 COMMUNISM IN CZECH.  RUS             365  1948       13       1
 7 BERLIN BLOCKADE      RUS             365  1948      340       4
 8 BERLIN BLOCKADE      UKG             200  1948      323       1
 9 BERLIN BLOCKADE      USA               2  1948      323       1
10 CHINA CIVIL WAR      USA               2  1948       34       4
# ℹ 77 more rows</code></pre>
</div>
</div>
<p>That certainly works fine to give us what we want, but it involved a lot of repetitive typing and retyping of <code>df_crises_cw &lt;- function_name(df_crises_cw, ...)</code>. And that’s only with fairly simple subsetting operations.</p>
<p>The <span class="concept">pipe operator</span> in R lets us chain together commands like this much more succinctly. <code>x |&gt; function_name(...)</code> is equivalent to <code>function_name(x, ...)</code> in R.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span></span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a>x</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  1  2  3  4  5  6  7  8  9 10</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(x)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5.5</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a>x <span class="sc">|&gt;</span> <span class="fu">mean</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5.5</code></pre>
</div>
</div>
<p>On its own the pipe might seem dumb, like just more typing for the same result. Weren’t we trying to reduce the amount of typing? The pipe is mainly useful when we are chaining many commands together.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Chained commands</span></span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">first_command</span>(x, arg1, arg2)</span>
<span id="cb101-3"><a href="#cb101-3" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">second_command</span>(y, arg3)</span>
<span id="cb101-4"><a href="#cb101-4" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">third_command</span>(y, arg4, arg5)</span>
<span id="cb101-5"><a href="#cb101-5" aria-hidden="true" tabindex="-1"></a><span class="fu">fourth_command</span>(y, arg6)</span>
<span id="cb101-6"><a href="#cb101-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-7"><a href="#cb101-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Same thing, but piped</span></span>
<span id="cb101-8"><a href="#cb101-8" aria-hidden="true" tabindex="-1"></a>x <span class="sc">|&gt;</span></span>
<span id="cb101-9"><a href="#cb101-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">first_command</span>(arg1, arg2) <span class="sc">|&gt;</span></span>
<span id="cb101-10"><a href="#cb101-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">second_command</span>(arg3) <span class="sc">|&gt;</span></span>
<span id="cb101-11"><a href="#cb101-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">third_command</span>(arg4, arg5) <span class="sc">|&gt;</span></span>
<span id="cb101-12"><a href="#cb101-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fourth_command</span>(arg6)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Let’s see the pipe in action in the context of our data cleaning example.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a>df_crises <span class="sc">|&gt;</span></span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb102-3"><a href="#cb102-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">crisis_name =</span> crisname,</span>
<span id="cb102-4"><a href="#cb102-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">actor_name =</span> actor,</span>
<span id="cb102-5"><a href="#cb102-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">actor_id =</span> cracid,</span>
<span id="cb102-6"><a href="#cb102-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">year =</span> systrgyr,</span>
<span id="cb102-7"><a href="#cb102-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">duration =</span> trgterra,</span>
<span id="cb102-8"><a href="#cb102-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">outcome =</span> outcom</span>
<span id="cb102-9"><a href="#cb102-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb102-10"><a href="#cb102-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">&gt;=</span> <span class="dv">1946</span> <span class="sc">&amp;</span> year <span class="sc">&lt;=</span> <span class="dv">1989</span>) <span class="sc">|&gt;</span></span>
<span id="cb102-11"><a href="#cb102-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(actor_name <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"USA"</span>, <span class="st">"RUS"</span>, <span class="st">"UKG"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 87 × 6
   crisis_name          actor_name actor_id  year duration outcome
   &lt;chr&gt;                &lt;chr&gt;         &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;
 1 COMMUNISM IN POLAND  RUS             365  1946      204       1
 2 TURKISH STRAITS      USA               2  1946       81       1
 3 COMMUNISM IN HUNGARY RUS             365  1947      112       1
 4 TRUMAN DOCTRINE      USA               2  1947       91       1
 5 MARSHALL PLAN        RUS             365  1947        9       1
 6 COMMUNISM IN CZECH.  RUS             365  1948       13       1
 7 BERLIN BLOCKADE      RUS             365  1948      340       4
 8 BERLIN BLOCKADE      UKG             200  1948      323       1
 9 BERLIN BLOCKADE      USA               2  1948      323       1
10 CHINA CIVIL WAR      USA               2  1948       34       4
# ℹ 77 more rows</code></pre>
</div>
</div>
<p>It might take a bit getting used to, but I personally find it much easier to use the pipe when going through the data cleaning process. One thing to keep in mind, just like when you run these commands the regular way, they won’t change your data frame in place. You need to explicitly assign the output to a variable name.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a>df_crises_cw <span class="ot">&lt;-</span> df_crises <span class="sc">|&gt;</span></span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb104-3"><a href="#cb104-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">crisis_name =</span> crisname,</span>
<span id="cb104-4"><a href="#cb104-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">actor_name =</span> actor,</span>
<span id="cb104-5"><a href="#cb104-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">actor_id =</span> cracid,</span>
<span id="cb104-6"><a href="#cb104-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">year =</span> systrgyr,</span>
<span id="cb104-7"><a href="#cb104-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">duration =</span> trgterra,</span>
<span id="cb104-8"><a href="#cb104-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">outcome =</span> outcom</span>
<span id="cb104-9"><a href="#cb104-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb104-10"><a href="#cb104-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">&gt;=</span> <span class="dv">1946</span> <span class="sc">&amp;</span> year <span class="sc">&lt;=</span> <span class="dv">1989</span>) <span class="sc">|&gt;</span></span>
<span id="cb104-11"><a href="#cb104-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(actor_name <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"USA"</span>, <span class="st">"RUS"</span>, <span class="st">"UKG"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Final note on the pipe. Until pretty recently, the pipe was <code>%&gt;%</code> instead of <code>|&gt;</code>. So you’ll see a lot of code on the Internet that uses <code>%&gt;%</code>. Don’t worry, it works exactly the same as <code>|&gt;</code> (except in some edge cases that won’t come up for us).</p>
<div class="callout callout-style-default callout-note callout-titled" title="In-class exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>In-class exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Use the pipe to create a data frame called <code>df_long_crises</code> with the following specs:</p>
<ul>
<li>Same variables as in my example, except with the numeric crisis ID instead of the crisis name</li>
<li>Only observations where the actor was involved in the crisis for 100+ days</li>
<li>Exclude observations of Russia from 1990 onward</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a><span class="co"># [Write your answer here]</span></span>
<span id="cb105-3"><a href="#cb105-3" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</section>
</section>
<section id="transforming" class="level2 page-columns page-full" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="transforming"><span class="header-section-number">2.3</span> Transforming</h2>
<section id="changing-variables-and-making-new-ones" class="level3 page-columns page-full" data-number="2.3.1">
<h3 data-number="2.3.1" class="anchored" data-anchor-id="changing-variables-and-making-new-ones"><span class="header-section-number">2.3.1</span> Changing variables and making new ones</h3>
<p>The <code>mutate()</code> function lets you change a column in the dataframe, or create a new column using the values in existing columns. For example, right now the duration of each crisis is measured in days. We can add new columns to measure duration in weeks and years instead. As always, if we want our new columns to persist instead of vanishing into the ether, we need to assign the output to a variable — either overwriting <code>df_crises_cw</code> or creating a new data frame.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a>df_crises_cw <span class="ot">&lt;-</span> df_crises_cw <span class="sc">|&gt;</span></span>
<span id="cb106-2"><a href="#cb106-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb106-3"><a href="#cb106-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">duration_weeks =</span> duration <span class="sc">/</span> <span class="dv">7</span>,</span>
<span id="cb106-4"><a href="#cb106-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">duration_years =</span> duration <span class="sc">/</span> <span class="dv">365</span></span>
<span id="cb106-5"><a href="#cb106-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb106-6"><a href="#cb106-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb106-7"><a href="#cb106-7" aria-hidden="true" tabindex="-1"></a>df_crises_cw</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 87 × 8
   crisis_name actor_name actor_id  year duration outcome duration_weeks
   &lt;chr&gt;       &lt;chr&gt;         &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;          &lt;dbl&gt;
 1 COMMUNISM … RUS             365  1946      204       1          29.1 
 2 TURKISH ST… USA               2  1946       81       1          11.6 
 3 COMMUNISM … RUS             365  1947      112       1          16   
 4 TRUMAN DOC… USA               2  1947       91       1          13   
 5 MARSHALL P… RUS             365  1947        9       1           1.29
 6 COMMUNISM … RUS             365  1948       13       1           1.86
 7 BERLIN BLO… RUS             365  1948      340       4          48.6 
 8 BERLIN BLO… UKG             200  1948      323       1          46.1 
 9 BERLIN BLO… USA               2  1948      323       1          46.1 
10 CHINA CIVI… USA               2  1948       34       4           4.86
# ℹ 77 more rows
# ℹ 1 more variable: duration_years &lt;dbl&gt;</code></pre>
</div>
</div>
<p>There’s a very useful function for mutating called <code>if_else()</code>. You invoke it as <code>if_else(condition, a, b)</code>:</p>
<ul>
<li><code>condition</code>: vector of <code>TRUE</code> and <code>FALSE</code> values</li>
<li><code>a</code>: value, or vector of values, to use for entries where <code>condition</code> is <code>TRUE</code></li>
<li><code>b</code>: value, or vector of values, to use for entries where <code>condition</code> is <code>FALSE</code></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simple if_else example</span></span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>)</span>
<span id="cb108-3"><a href="#cb108-3" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">100</span>, <span class="sc">-</span><span class="dv">200</span>, <span class="dv">300</span>, <span class="dv">400</span>)</span>
<span id="cb108-4"><a href="#cb108-4" aria-hidden="true" tabindex="-1"></a><span class="fu">if_else</span>(x <span class="sc">&gt;</span> y, x, y)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]   1   2 300 400</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="fu">if_else</span>(x <span class="sc">&gt;</span> y, <span class="st">"ice cream"</span>, <span class="st">"pizza"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "ice cream" "ice cream" "pizza"     "pizza"    </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="In-class exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>In-class exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Use <code>mutate()</code> and <code>if_else()</code> together to add another column to <code>df_crises_cw</code> called <code>crisis_length</code>. This variable should say <code>"long"</code> if the crisis is 100 or more days, and <code>"short"</code> otherwise.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb112-2"><a href="#cb112-2" aria-hidden="true" tabindex="-1"></a><span class="co"># [Write your answer here]</span></span>
<span id="cb112-3"><a href="#cb112-3" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
<p>The “outcome” variable here is recorded as numbers, which stand for different categories of crisis outcomes. The <a href="https://duke.box.com/s/l4glcl5jaipmycs7unzraxkp92w1nh3d">ICB codebook</a> explains which category is associated with each numerical value.</p>
<ol type="1">
<li>Victory: this country achieved its basic goals.</li>
<li>Compromise: this country partly achieved its basic goals.</li>
<li>Stalemate: there was no major change in the situation.</li>
<li>Defeat: this country did not achieve its basic goals, and instead yielded or surrendered.</li>
<li>Other.</li>
</ol>
<p>So for example, looking at the rows associated with the Berlin Blockade, we see that the USA and United Kingdom experienced victory, while the Soviet Union was defeated.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a>df_crises_cw <span class="sc">|&gt;</span></span>
<span id="cb113-2"><a href="#cb113-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(crisis_name <span class="sc">==</span> <span class="st">"BERLIN BLOCKADE"</span>) <span class="sc">|&gt;</span></span>
<span id="cb113-3"><a href="#cb113-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(actor_name, outcome, <span class="fu">everything</span>())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 8
  actor_name outcome crisis_name  actor_id  year duration duration_weeks
  &lt;chr&gt;        &lt;dbl&gt; &lt;chr&gt;           &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;          &lt;dbl&gt;
1 RUS              4 BERLIN BLOC…      365  1948      340           48.6
2 UKG              1 BERLIN BLOC…      200  1948      323           46.1
3 USA              1 BERLIN BLOC…        2  1948      323           46.1
# ℹ 1 more variable: duration_years &lt;dbl&gt;</code></pre>
</div>
</div>
<p>We <em>could</em> use a sequence of 5 <code>if_else()</code> statements to convert the <code>outcome</code> variable in terms of category names instead of (hard to remember) numeric identifiers. But it’s easier to use <code>case_when()</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a>df_crises_cw <span class="ot">&lt;-</span> df_crises_cw <span class="sc">|&gt;</span></span>
<span id="cb115-2"><a href="#cb115-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb115-3"><a href="#cb115-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">outcome =</span> <span class="fu">case_when</span>(</span>
<span id="cb115-4"><a href="#cb115-4" aria-hidden="true" tabindex="-1"></a>      outcome <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">"victory"</span>,</span>
<span id="cb115-5"><a href="#cb115-5" aria-hidden="true" tabindex="-1"></a>      outcome <span class="sc">==</span> <span class="dv">2</span> <span class="sc">~</span> <span class="st">"compromise"</span>,</span>
<span id="cb115-6"><a href="#cb115-6" aria-hidden="true" tabindex="-1"></a>      outcome <span class="sc">==</span> <span class="dv">3</span> <span class="sc">~</span> <span class="st">"stalemate"</span>,</span>
<span id="cb115-7"><a href="#cb115-7" aria-hidden="true" tabindex="-1"></a>      outcome <span class="sc">==</span> <span class="dv">4</span> <span class="sc">~</span> <span class="st">"defeat"</span>,</span>
<span id="cb115-8"><a href="#cb115-8" aria-hidden="true" tabindex="-1"></a>      outcome <span class="sc">==</span> <span class="dv">5</span> <span class="sc">~</span> <span class="st">"other"</span></span>
<span id="cb115-9"><a href="#cb115-9" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb115-10"><a href="#cb115-10" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb115-11"><a href="#cb115-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb115-12"><a href="#cb115-12" aria-hidden="true" tabindex="-1"></a>df_crises_cw</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 87 × 8
   crisis_name actor_name actor_id  year duration outcome duration_weeks
   &lt;chr&gt;       &lt;chr&gt;         &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;            &lt;dbl&gt;
 1 COMMUNISM … RUS             365  1946      204 victory          29.1 
 2 TURKISH ST… USA               2  1946       81 victory          11.6 
 3 COMMUNISM … RUS             365  1947      112 victory          16   
 4 TRUMAN DOC… USA               2  1947       91 victory          13   
 5 MARSHALL P… RUS             365  1947        9 victory           1.29
 6 COMMUNISM … RUS             365  1948       13 victory           1.86
 7 BERLIN BLO… RUS             365  1948      340 defeat           48.6 
 8 BERLIN BLO… UKG             200  1948      323 victory          46.1 
 9 BERLIN BLO… USA               2  1948      323 victory          46.1 
10 CHINA CIVI… USA               2  1948       34 defeat            4.86
# ℹ 77 more rows
# ℹ 1 more variable: duration_years &lt;dbl&gt;</code></pre>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="margin-aside">
<p>There’s another function called <code>case_match()</code> that would let you do this same thing with even less typing. Go ahead, look it up, and use it if you like! But <code>case_when()</code> is a bit more flexible, so to avoid confusion I’m only going to use it.</p>
</div></div></section>
<section id="grouping-and-summarizing" class="level3" data-number="2.3.2">
<h3 data-number="2.3.2" class="anchored" data-anchor-id="grouping-and-summarizing"><span class="header-section-number">2.3.2</span> Grouping and summarizing</h3>
<p>The <code>summarize()</code> function lets us calculate summaries of columns in the data. For example, let’s find the shortest, longest, and average crisis durations among the USA/UK/USSR during the Cold War.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a>df_crises_cw <span class="sc">|&gt;</span></span>
<span id="cb117-2"><a href="#cb117-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb117-3"><a href="#cb117-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">shortest =</span> <span class="fu">min</span>(duration),</span>
<span id="cb117-4"><a href="#cb117-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">longest =</span> <span class="fu">max</span>(duration),</span>
<span id="cb117-5"><a href="#cb117-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">average =</span> <span class="fu">mean</span>(duration)</span>
<span id="cb117-6"><a href="#cb117-6" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  shortest longest average
     &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
1        2     486    99.2</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Seemingly easier way</span></span>
<span id="cb119-2"><a href="#cb119-2" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(df_crises_cw<span class="sc">$</span>duration)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(df_crises_cw<span class="sc">$</span>duration)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 486</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(df_crises_cw<span class="sc">$</span>duration)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 99.24138</code></pre>
</div>
</div>
<p>The real power of <code>summarize()</code> comes in when you combine it with <code>group_by()</code> to calculate summaries for subcategories of the data. For example, say we wanted to calculate the shortest, longest, and average crisis duration separately for the USA, UK, and USSR. That would be tedious to do the “normal” way:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb125"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a><span class="co"># one of nine long expressions you'd have to type out</span></span>
<span id="cb125-2"><a href="#cb125-2" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(df_crises_cw<span class="sc">$</span>duration[df_crises_cw<span class="sc">$</span>actor_name <span class="sc">==</span> <span class="st">"USA"</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
</div>
<p><code>group_by |&gt; summarize</code> makes this <em>much</em> easier.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a>df_crises_cw <span class="sc">|&gt;</span></span>
<span id="cb127-2"><a href="#cb127-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(actor_name) <span class="sc">|&gt;</span></span>
<span id="cb127-3"><a href="#cb127-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb127-4"><a href="#cb127-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">shortest =</span> <span class="fu">min</span>(duration),</span>
<span id="cb127-5"><a href="#cb127-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">longest =</span> <span class="fu">max</span>(duration),</span>
<span id="cb127-6"><a href="#cb127-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">average =</span> <span class="fu">mean</span>(duration)</span>
<span id="cb127-7"><a href="#cb127-7" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  actor_name shortest longest average
  &lt;chr&gt;         &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
1 RUS               3     486   124. 
2 UKG              12     323   106  
3 USA               2     433    84.6</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="In-class exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>In-class exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>In which year of the Cold War did the USA spend the most total days in crises? Use <code>filter()</code>, <code>group_by()</code>, <code>summarize()</code>, and <code>arrange()</code> together to figure it out.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb129-2"><a href="#cb129-2" aria-hidden="true" tabindex="-1"></a><span class="co"># [Write your answer here]</span></span>
<span id="cb129-3"><a href="#cb129-3" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
<p>What if you wanted to count the number of crises involving each country? There’s a special function called <code>n()</code> that counts the number of observations within each group.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb130"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb130-1"><a href="#cb130-1" aria-hidden="true" tabindex="-1"></a>df_crises_cw <span class="sc">|&gt;</span></span>
<span id="cb130-2"><a href="#cb130-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(actor_name) <span class="sc">|&gt;</span></span>
<span id="cb130-3"><a href="#cb130-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">number =</span> <span class="fu">n</span>())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  actor_name number
  &lt;chr&gt;       &lt;int&gt;
1 RUS            24
2 UKG            15
3 USA            48</code></pre>
</div>
</div>
<p>You can group on multiple variables at once. The number of rows in the result will be the number of unique combinations of values across the grouping variables.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb132"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb132-1"><a href="#cb132-1" aria-hidden="true" tabindex="-1"></a>df_crises_cw <span class="sc">|&gt;</span></span>
<span id="cb132-2"><a href="#cb132-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(actor_name, outcome) <span class="sc">|&gt;</span></span>
<span id="cb132-3"><a href="#cb132-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb132-4"><a href="#cb132-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">number =</span> <span class="fu">n</span>(),</span>
<span id="cb132-5"><a href="#cb132-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">shortest =</span> <span class="fu">min</span>(duration),</span>
<span id="cb132-6"><a href="#cb132-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">longest =</span> <span class="fu">max</span>(duration)</span>
<span id="cb132-7"><a href="#cb132-7" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'actor_name'. You can override
using the `.groups` argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 13 × 5
# Groups:   actor_name [3]
   actor_name outcome    number shortest longest
   &lt;chr&gt;      &lt;chr&gt;       &lt;int&gt;    &lt;dbl&gt;   &lt;dbl&gt;
 1 RUS        compromise      3        8     222
 2 RUS        defeat          5        3     340
 3 RUS        stalemate       3        9     260
 4 RUS        victory        13        9     486
 5 UKG        compromise      2      183     192
 6 UKG        defeat          2       66     104
 7 UKG        other           1       17      17
 8 UKG        stalemate       2      112     293
 9 UKG        victory         8       12     323
10 USA        compromise      7        4     433
11 USA        defeat          6       10     336
12 USA        stalemate       8        5     293
13 USA        victory        27        2     323</code></pre>
</div>
</div>
</section>
</section>
<section id="reshaping" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="reshaping"><span class="header-section-number">2.4</span> Reshaping</h2>
<p>To get practice with reshaping and merging data, we’re going to bring in a second dataset. <code>military.csv</code>, stored at <a href="https://bkenkel.com/qps1/data/military.csv" class="uri">https://bkenkel.com/qps1/data/military.csv</a>, contains data on military spending and force sizes by country from 1816 to 2019.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb135"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb135-1"><a href="#cb135-1" aria-hidden="true" tabindex="-1"></a>df_military <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://bkenkel.com/qps1/data/military.csv"</span>)</span>
<span id="cb135-2"><a href="#cb135-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb135-3"><a href="#cb135-3" aria-hidden="true" tabindex="-1"></a>df_military</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 31,902 × 5
   ccode stateabb  year mil_indicator amount
   &lt;dbl&gt; &lt;chr&gt;    &lt;dbl&gt; &lt;chr&gt;          &lt;dbl&gt;
 1     2 USA       1816 spending        3823
 2     2 USA       1816 personnel         17
 3     2 USA       1817 spending        2466
 4     2 USA       1817 personnel         15
 5     2 USA       1818 spending        1910
 6     2 USA       1818 personnel         14
 7     2 USA       1819 spending        2301
 8     2 USA       1819 personnel         13
 9     2 USA       1820 spending        1556
10     2 USA       1820 personnel         15
# ℹ 31,892 more rows</code></pre>
</div>
</div>
<p>The amounts here are in thousands of dollars and people respectively. For example, looking at the first two rows, in 1816 the USA spent $3.8 million on the military, which consisted of 17,000 soldiers.</p>
<p>How can we reshape this data so that there’s a single row for the USA in 1816, a single row for the USA in 1817, and so on? As of now the data is “longer” than we want it to be, and we’d like it to be “wider”. Hence we’ll use the function <code>pivot_wider()</code>. Here’s how we use it.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb137"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb137-1"><a href="#cb137-1" aria-hidden="true" tabindex="-1"></a>df_military_wide <span class="ot">&lt;-</span> df_military <span class="sc">|&gt;</span></span>
<span id="cb137-2"><a href="#cb137-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> mil_indicator, <span class="at">values_from =</span> amount)</span>
<span id="cb137-3"><a href="#cb137-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb137-4"><a href="#cb137-4" aria-hidden="true" tabindex="-1"></a>df_military_wide</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 15,951 × 5
   ccode stateabb  year spending personnel
   &lt;dbl&gt; &lt;chr&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
 1     2 USA       1816     3823        17
 2     2 USA       1817     2466        15
 3     2 USA       1818     1910        14
 4     2 USA       1819     2301        13
 5     2 USA       1820     1556        15
 6     2 USA       1821     1612        11
 7     2 USA       1822     1079        10
 8     2 USA       1823     1170        11
 9     2 USA       1824     1261        11
10     2 USA       1825     1336        11
# ℹ 15,941 more rows</code></pre>
</div>
</div>
<p>Making a data frame “wider” means taking data that’s currently stored row by row, and spreading it out across columns instead. The <code>names_from</code> argument tells <code>pivot_wider()</code> which column of the original data frame contains the names of the new columns we want to create. The <code>values_from</code> argument tells it which column contains the values that we want to put into each column.</p>
<div class="callout callout-style-default callout-note callout-titled" title="In-class exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>In-class exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Go back to our data on the USA, UK, and USSR in Cold War crises. Use <code>pivot_wider()</code> to create a new data frame where each row is a unique crisis name, and there are columns for the USA, UK, and USSR telling that country’s outcome from the given crisis. Were there any crises that ended in victory for both the USA and the USSR?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb139"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb139-1"><a href="#cb139-1" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb139-2"><a href="#cb139-2" aria-hidden="true" tabindex="-1"></a><span class="co"># [Write your answer here]</span></span>
<span id="cb139-3"><a href="#cb139-3" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
<p>The opposite of <code>pivot_wider()</code> is, naturally enough, <code>pivot_longer()</code>. For example, imagine your raw data had a single row for each country, then a separate column for its military spending each year.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb140"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb140-1"><a href="#cb140-1" aria-hidden="true" tabindex="-1"></a>df_too_wide <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb140-2"><a href="#cb140-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">ccode =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">200</span>, <span class="dv">365</span>),</span>
<span id="cb140-3"><a href="#cb140-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">stateabb =</span> <span class="fu">c</span>(<span class="st">"USA"</span>, <span class="st">"UKG"</span>, <span class="st">"RUS"</span>),</span>
<span id="cb140-4"><a href="#cb140-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">mil1816 =</span> <span class="fu">c</span>(<span class="dv">17</span>, <span class="dv">255</span>, <span class="dv">800</span>),</span>
<span id="cb140-5"><a href="#cb140-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">mil1817 =</span> <span class="fu">c</span>(<span class="dv">15</span>, <span class="dv">190</span>, <span class="dv">700</span>),</span>
<span id="cb140-6"><a href="#cb140-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">mil1818 =</span> <span class="fu">c</span>(<span class="dv">14</span>, <span class="dv">173</span>, <span class="dv">600</span>)</span>
<span id="cb140-7"><a href="#cb140-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb140-8"><a href="#cb140-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb140-9"><a href="#cb140-9" aria-hidden="true" tabindex="-1"></a>df_too_wide</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  ccode stateabb mil1816 mil1817 mil1818
  &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
1     2 USA           17      15      14
2   200 UKG          255     190     173
3   365 RUS          800     700     600</code></pre>
</div>
</div>
<p>To use <code>pivot_longer()</code>, we have to tell it (1) the set of columns whose values we want to collapse into a single column, (2) what we want to name the column that stores the column names from the original data, and (3) what we want to name the column that stores the values.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb142"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb142-1"><a href="#cb142-1" aria-hidden="true" tabindex="-1"></a>df_too_wide <span class="sc">|&gt;</span></span>
<span id="cb142-2"><a href="#cb142-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb142-3"><a href="#cb142-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">starts_with</span>(<span class="st">"mil"</span>),</span>
<span id="cb142-4"><a href="#cb142-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">"year"</span>,</span>
<span id="cb142-5"><a href="#cb142-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">"personnel"</span></span>
<span id="cb142-6"><a href="#cb142-6" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 4
  ccode stateabb year    personnel
  &lt;dbl&gt; &lt;chr&gt;    &lt;chr&gt;       &lt;dbl&gt;
1     2 USA      mil1816        17
2     2 USA      mil1817        15
3     2 USA      mil1818        14
4   200 UKG      mil1816       255
5   200 UKG      mil1817       190
6   200 UKG      mil1818       173
7   365 RUS      mil1816       800
8   365 RUS      mil1817       700
9   365 RUS      mil1818       600</code></pre>
</div>
</div>
<p>FYI: If you wanted to turn the year column there into a proper year, you could <code>mutate()</code> it to remove the “mil” text and then convert it to a number.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb144"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb144-1"><a href="#cb144-1" aria-hidden="true" tabindex="-1"></a>df_too_wide <span class="sc">|&gt;</span></span>
<span id="cb144-2"><a href="#cb144-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb144-3"><a href="#cb144-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">starts_with</span>(<span class="st">"mil"</span>),</span>
<span id="cb144-4"><a href="#cb144-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">"year"</span>,</span>
<span id="cb144-5"><a href="#cb144-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">"personnel"</span></span>
<span id="cb144-6"><a href="#cb144-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb144-7"><a href="#cb144-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb144-8"><a href="#cb144-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">year =</span> <span class="fu">str_replace</span>(year, <span class="st">"mil"</span>, <span class="st">""</span>),</span>
<span id="cb144-9"><a href="#cb144-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">year =</span> <span class="fu">as.numeric</span>(year)</span>
<span id="cb144-10"><a href="#cb144-10" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 4
  ccode stateabb  year personnel
  &lt;dbl&gt; &lt;chr&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1     2 USA       1816        17
2     2 USA       1817        15
3     2 USA       1818        14
4   200 UKG       1816       255
5   200 UKG       1817       190
6   200 UKG       1818       173
7   365 RUS       1816       800
8   365 RUS       1817       700
9   365 RUS       1818       600</code></pre>
</div>
</div>
<p>How did I know to use the <code>str_replace()</code> function there? The <code>stringr</code> package contains tons of helpful functions for manipulating text in R. You can see everything it does by googling the documentation for it, or by entering <code>help(package = "stringr")</code> at the R console.</p>
</section>
<section id="merging" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="merging"><span class="header-section-number">2.5</span> Merging</h2>
<p>Data work in political science often involves combining data from multiple sources. For example, here we have one dataset on country participation in international crises, and another on the size of their militaries. How can we put these together?</p>
<p>The first thing to do is decide which dataset should be the “base” that we merge other data sources into. What’s appropriate depends on the question you’re trying to answer. For our purposes here, let’s imagine we want to know whether crisis winners tend to spend more on their military than crisis losers. That means we only care about the countries that actually ended up in crises, so we should use the crisis data as our base and merge the military size data into that.</p>
<p>The next thing we need to make sure of is that we have some way to identify the same observation across datasets. Here we are going to match observations by the numerical “country code” and by year. First we’ll edit the military size data so that the country code indicator has the same name as in <code>df_crises_cw</code>. (We’ll also drop the country name variable, since we already have that in the original data.)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb146"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb146-1"><a href="#cb146-1" aria-hidden="true" tabindex="-1"></a>df_military_wide <span class="ot">&lt;-</span> df_military_wide <span class="sc">|&gt;</span></span>
<span id="cb146-2"><a href="#cb146-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">actor_id =</span> ccode) <span class="sc">|&gt;</span></span>
<span id="cb146-3"><a href="#cb146-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>stateabb)</span>
<span id="cb146-4"><a href="#cb146-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb146-5"><a href="#cb146-5" aria-hidden="true" tabindex="-1"></a>df_military_wide</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 15,951 × 4
   actor_id  year spending personnel
      &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
 1        2  1816     3823        17
 2        2  1817     2466        15
 3        2  1818     1910        14
 4        2  1819     2301        13
 5        2  1820     1556        15
 6        2  1821     1612        11
 7        2  1822     1079        10
 8        2  1823     1170        11
 9        2  1824     1261        11
10        2  1825     1336        11
# ℹ 15,941 more rows</code></pre>
</div>
</div>
<p>Next we’ll use <code>left_join()</code> to merge the datasets together. We need to tell this function three things:</p>
<ul>
<li>The data frame to use as our base.</li>
<li>The data frame that we want to merge values in from.</li>
<li>The column names to match observations by.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb148"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb148-1"><a href="#cb148-1" aria-hidden="true" tabindex="-1"></a>df_crisis_and_mil <span class="ot">&lt;-</span> <span class="fu">left_join</span>(</span>
<span id="cb148-2"><a href="#cb148-2" aria-hidden="true" tabindex="-1"></a>  df_crises_cw,</span>
<span id="cb148-3"><a href="#cb148-3" aria-hidden="true" tabindex="-1"></a>  df_military_wide,</span>
<span id="cb148-4"><a href="#cb148-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"actor_id"</span>, <span class="st">"year"</span>)</span>
<span id="cb148-5"><a href="#cb148-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb148-6"><a href="#cb148-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb148-7"><a href="#cb148-7" aria-hidden="true" tabindex="-1"></a>df_crisis_and_mil</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 87 × 10
   crisis_name actor_name actor_id  year duration outcome duration_weeks
   &lt;chr&gt;       &lt;chr&gt;         &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;            &lt;dbl&gt;
 1 COMMUNISM … RUS             365  1946      204 victory          29.1 
 2 TURKISH ST… USA               2  1946       81 victory          11.6 
 3 COMMUNISM … RUS             365  1947      112 victory          16   
 4 TRUMAN DOC… USA               2  1947       91 victory          13   
 5 MARSHALL P… RUS             365  1947        9 victory           1.29
 6 COMMUNISM … RUS             365  1948       13 victory           1.86
 7 BERLIN BLO… RUS             365  1948      340 defeat           48.6 
 8 BERLIN BLO… UKG             200  1948      323 victory          46.1 
 9 BERLIN BLO… USA               2  1948      323 victory          46.1 
10 CHINA CIVI… USA               2  1948       34 defeat            4.86
# ℹ 77 more rows
# ℹ 3 more variables: duration_years &lt;dbl&gt;, spending &lt;dbl&gt;,
#   personnel &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Now we can use <code>group_by()</code> and <code>summarize()</code> to calculate the average size and spending of the military among crisis winners, crisis losers, and so on.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb150"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb150-1"><a href="#cb150-1" aria-hidden="true" tabindex="-1"></a>df_crisis_and_mil <span class="sc">|&gt;</span></span>
<span id="cb150-2"><a href="#cb150-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(outcome) <span class="sc">|&gt;</span></span>
<span id="cb150-3"><a href="#cb150-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">avg_spending =</span> <span class="fu">mean</span>(spending),</span>
<span id="cb150-4"><a href="#cb150-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">avg_personnel =</span> <span class="fu">mean</span>(personnel))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 3
  outcome    avg_spending avg_personnel
  &lt;chr&gt;             &lt;dbl&gt;         &lt;dbl&gt;
1 compromise    57787476.         2436.
2 defeat        57416910.         2638.
3 other          4409778           839 
4 stalemate     81993296          2714.
5 victory       65411474.         2568.</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="In-class exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>In-class exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Winners have smaller militaries than losers on average. Does this mean that increasing the size of your military actually hurts your ability to win a crisis? Why or why not? How could you dig deeper into the data to better figure out whether this is the case?</p>
<blockquote class="blockquote">
<p>[Write your answer here]</p>
</blockquote>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./intro_r.html" class="pagination-link" aria-label="Introduction to R">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to R</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./univariate_analysis.html" class="pagination-link" aria-label="Univariate Analysis">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Univariate Analysis</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p xmlns:cc="http://creativecommons.org/ns#" class="cc-footer">
This work is licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-NC-SA 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1" alt=""></a>
</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>