<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>3&nbsp; Univariate Analysis – Quantitative Political Science I</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./data_visualization.html" rel="next">
<link href="./data_wrangling.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-d19a348d1c3c577774653d463d75021c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked slimcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./univariate_analysis.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Univariate Analysis</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Quantitative Political Science I</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro_r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_wrangling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data Wrangling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./univariate_analysis.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Univariate Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data Visualization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./correlation_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Correlation and Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./simulation_resampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Simulation and Resampling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./using_chatgpt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Using ChatGPT</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_sources.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Data Sources</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#data-county-level-presidential-election-results" id="toc-data-county-level-presidential-election-results" class="nav-link active" data-scroll-target="#data-county-level-presidential-election-results"><span class="header-section-number">3.1</span> Data: County-level presidential election results</a></li>
  <li><a href="#central-tendency-whats-a-typical-value" id="toc-central-tendency-whats-a-typical-value" class="nav-link" data-scroll-target="#central-tendency-whats-a-typical-value"><span class="header-section-number">3.2</span> Central tendency: What’s a typical value?</a>
  <ul class="collapse">
  <li><a href="#continuous-variables" id="toc-continuous-variables" class="nav-link" data-scroll-target="#continuous-variables"><span class="header-section-number">3.2.1</span> Continuous variables</a></li>
  <li><a href="#unordered-categorical-variables" id="toc-unordered-categorical-variables" class="nav-link" data-scroll-target="#unordered-categorical-variables"><span class="header-section-number">3.2.2</span> Unordered categorical variables</a></li>
  <li><a href="#ordered-categorical-variables" id="toc-ordered-categorical-variables" class="nav-link" data-scroll-target="#ordered-categorical-variables"><span class="header-section-number">3.2.3</span> Ordered categorical variables</a></li>
  <li><a href="#binary-variables" id="toc-binary-variables" class="nav-link" data-scroll-target="#binary-variables"><span class="header-section-number">3.2.4</span> Binary variables</a></li>
  </ul></li>
  <li><a href="#spread-how-far-from-the-central-tendency-is-typical" id="toc-spread-how-far-from-the-central-tendency-is-typical" class="nav-link" data-scroll-target="#spread-how-far-from-the-central-tendency-is-typical"><span class="header-section-number">3.3</span> Spread: How far from the central tendency is typical?</a>
  <ul class="collapse">
  <li><a href="#sec-standard-deviation" id="toc-sec-standard-deviation" class="nav-link" data-scroll-target="#sec-standard-deviation"><span class="header-section-number">3.3.1</span> Standard deviation</a></li>
  <li><a href="#median-absolute-deviation" id="toc-median-absolute-deviation" class="nav-link" data-scroll-target="#median-absolute-deviation"><span class="header-section-number">3.3.2</span> Median absolute deviation</a></li>
  <li><a href="#sec-quartiles" id="toc-sec-quartiles" class="nav-link" data-scroll-target="#sec-quartiles"><span class="header-section-number">3.3.3</span> Quartiles and other percentages</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-univariate-analysis" class="quarto-section-identifier"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Univariate Analysis</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>By now you’re experts on wrangling data. It’s time to start using data to learn about politics.</p>
<p>We will start by analyzing a single variable at a time. Our goal is to come up with good quantitative <span class="concept">summaries</span> of each variable in our data — i.e., to collapse the complexity of what we observe into a few numerical values that are easier to wrap our minds around. The major concepts we will hit are:</p>
<ol type="1">
<li><p>Measures of <span class="concept">central tendency</span>, which tell us what a “typical value” of a variable looks like. There’s no single best way to do this — the best measure of central tendency depends on what you’re trying to understand or accomplish with your data analysis.</p></li>
<li><p>Measures of <span class="concept">spread</span>, which tell us how far apart the values of the variable tend to be. Is a random observation from the data likely to be pretty close to the average (low spread) or far away from the average (high spread)?</p></li>
<li><p>We’ll discuss how the appropriate measures depend on the <span class="concept">type of variable</span> we’re dealing with.</p></li>
</ol>
<section id="data-county-level-presidential-election-results" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="data-county-level-presidential-election-results"><span class="header-section-number">3.1</span> Data: County-level presidential election results</h2>
<p>We will work with the data file <code>county_pres.csv</code>, stored online at <a href="https://bkenkel.com/qps1/data/county_pres.csv" class="uri">https://bkenkel.com/qps1/data/county_pres.csv</a>, which records county-by-county results of US presidential elections from 2000 to 2020.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"tidyverse"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>df_county_pres <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://bkenkel.com/qps1/data/county_pres.csv"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(df_county_pres)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 22,093
Columns: 12
$ year            &lt;dbl&gt; 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, …
$ state           &lt;chr&gt; "ALABAMA", "ALABAMA", "ALABAMA", "ALABAMA", "ALABAMA",…
$ region          &lt;chr&gt; "South", "South", "South", "South", "South", "South", …
$ county          &lt;chr&gt; "AUTAUGA", "BALDWIN", "BARBOUR", "BIBB", "BLOUNT", "BU…
$ county_fips     &lt;chr&gt; "01001", "01003", "01005", "01007", "01009", "01011", …
$ total_votes     &lt;dbl&gt; 17208, 56480, 10395, 7101, 17973, 4904, 7803, 38909, 1…
$ dem_votes       &lt;dbl&gt; 4942, 13997, 5188, 2710, 4977, 3395, 3606, 15781, 5616…
$ rep_votes       &lt;dbl&gt; 11993, 40872, 5096, 4273, 12667, 1433, 4127, 22306, 60…
$ margin          &lt;dbl&gt; -7051, -26875, 92, -1563, -7690, 1962, -521, -6525, -4…
$ pct_margin      &lt;dbl&gt; -0.409751278, -0.475832153, 0.008850409, -0.220109844,…
$ competitiveness &lt;dbl&gt; -3, -3, 0, -3, -3, 3, -1, -2, 0, -1, -3, 0, -2, -3, -3…
$ dem_win_state   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …</code></pre>
</div>
</div>
<p>Each observation (row) in this dataset is a particular county in a particular year. Here are all of the variables (columns) in the data, though we’ll only be using some of them in class today:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 76%">
</colgroup>
<thead>
<tr class="header">
<th>Name</th>
<th>Definition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>year</code></td>
<td>Election year</td>
</tr>
<tr class="even">
<td><code>state</code></td>
<td>State name</td>
</tr>
<tr class="odd">
<td><code>region</code></td>
<td>Region of the country (US Census codings) the state is in</td>
</tr>
<tr class="even">
<td><code>county</code></td>
<td>County name</td>
</tr>
<tr class="odd">
<td><code>county_fips</code></td>
<td>County FIPS (Federical Information Processing Standards) code</td>
</tr>
<tr class="even">
<td><code>total_votes</code></td>
<td>Total votes cast for any candidate in presidential race</td>
</tr>
<tr class="odd">
<td><code>dem_votes</code></td>
<td>Votes cast for the Democratic presidential candidate</td>
</tr>
<tr class="even">
<td><code>rep_votes</code></td>
<td>Votes cast for the Republican presidential candidate</td>
</tr>
<tr class="odd">
<td><code>margin</code></td>
<td>Difference in votes cast: <code>dem_votes - rep_votes</code></td>
</tr>
<tr class="even">
<td><code>pct_margin</code></td>
<td>Difference relative to total votes: <code>margin / total_votes</code></td>
</tr>
<tr class="odd">
<td><code>competitiveness</code></td>
<td>Categorization from -3 to +3 of how close the result was</td>
</tr>
<tr class="even">
<td><code>dem_win_state</code></td>
<td>Did the Democrat win the state? 0 = No, 1 = Yes</td>
</tr>
</tbody>
</table>
<p>We’re going to use this data to try to answer some simple questions about the competitiveness of presidential elections.</p>
<ul>
<li><p>How competitive are recent presidential elections?</p></li>
<li><p>Are they getting more or less competitive?</p></li>
<li><p>Which places are competitive and non-competitive?</p></li>
</ul>
<p>Data will help us answer these questions objectively, but any data analysis also involves judgment calls. For example, how should we define competitiveness? Is it closeness of the absolute number of votes, or of the vote percentages, or something else entirely? Can we sort races into “competitive” and “not competitive”, or does competitiveness lie on a continuum? Is competitiveness best assessed at the county, state, regional, or national level?</p>
<p>The important thing is to keep in mind the <u>purpose</u> of your data analysis. What are you trying to learn? What decisions are you hoping to make? If you’re working for a campaign and trying to help decide how to spend the advertising budget, the right notion of “competitiveness” might be different than if you’re a political science professor studying the effects of the economy on electoral competition. No matter what decision you make, it’s crucial that you:</p>
<ol type="1">
<li><p>Put some thought and reasoning into the judgment calls you make.</p></li>
<li><p>Be clear and transparent with your audience about which decisions you made, and why.</p></li>
<li><p>Be open to thinking about your problem in a different way! Try out alternative measures, conceptualizations, choices, etc., and see how sensitive your conclusions are.</p></li>
</ol>
</section>
<section id="central-tendency-whats-a-typical-value" class="level2 page-columns page-full" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="central-tendency-whats-a-typical-value"><span class="header-section-number">3.2</span> Central tendency: What’s a typical value?</h2>
<!--
In the next paragraph you'll see me use syntax like 22093, except with backticks in place of the apostrophes.
This lets us put the results of R code "in line" instead of in a separate code block.
-->
<p>Data analysis is all about summarizing. Think about our county-level presidential vote data. We’ve got 22093 rows and 12 columns, for a whopping 265116 separate pieces of information — and this isn’t even a particularly “big” dataset! In order to wrap our puny human brains around this much information, we need to find ways to summarize it much more concisely.</p>
<p>One way to summarize a variable is to characterize its <span class="concept">central tendency</span>: to answer the question “what’s a typical value for this variable?” For any variable, there are multiple different measures of central tendency available to us, and it is a judgment call which of them are most useful for a given purpose. But to even know what our options are, we have to know what kind of variable we are dealing with.</p>
<section id="continuous-variables" class="level3 page-columns page-full" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="continuous-variables"><span class="header-section-number">3.2.1</span> Continuous variables</h3>
<p>By the strictest definition, a <span class="concept">continuous variable</span> is a variable whose values may lie in a continuum of numbers. The height of a person is a continuous variable: they might be 66 inches tall, or 66.5 inches tall, or 66.52 inches tall, or even 66.5240549 inches tall. We aren’t going to be <em>that</em> strict about continuous variables. A candidate can receive 10,000 votes or 10,001 votes, but she can’t receive 10,000.5 votes. Nonetheless, vote totals are close enough that we will treat them as continuous. What’s really important, for our purposes, is that it makes sense to add and subtract the values of continuous variables.</p>
<p>In other stats classes you may have heard of a further subdivision of continuous variables into “interval” and “ratio” variables. Typical measures of central tendency (and spread, covered below) don’t care about this distinction, so we won’t either.</p>
<!-- When I put things between dollar signs, Quarto treats it as mathematical notation, using LaTeX syntax.  You won't need to use this in your problem sets, though you can if you want to be fancy. -->
<p>One of the most common measures of central tendency for a continuous variable is the <span class="concept">mean</span>, also called the average. To calculate the mean, we add up all the values of the variable, then divide by the number of observations. If there are <span class="math inline">\(N\)</span> observations of a continuous variable, say <span class="math inline">\(x_1, x_2, \ldots, x_N\)</span>, then the mean is <span class="math display">\[\bar{x} = \frac{\sum_{i=1}^N x_i}{N}.\]</span></p>
<p>As you saw a bit in our section on data wrangling, we can use the <code>mean()</code> function in R to calculate the mean. For example, let’s calculate the average number of votes in a county across the 2000–2020 presidential elections.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(df_county_pres<span class="sc">$</span>total_votes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 44419.82</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="In-class exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
In-class exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Calculate the average percentage by which Joe Biden won/lost across all counties in 2020. How does your result compare to his 4.5 percentage point margin of victory in the national popular vote? If there is a substantial difference, why do you think that is?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># [Write your answer here]</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<p>Sometimes when you calculate an average, you want to place more weight on some observations than others. This is common with survey data. For example, imagine you have a survey sample where 50% of respondents have a college degree and 50% do not. In the overall population, we know that about 38% of American adults have a college degree and 62% do not. So if you are trying to create a representative estimate, you might want to downweight the degree-holding respondents who are overrepresented in your sample, and upweight the degree-less respondents who are underrepresented. We call this a <span class="concept">weighted mean</span>.</p>
<p>For the math lovers out there, we define a weighted mean by associating positive weights <span class="math inline">\(w_1, w_2, \ldots, w_N\)</span> with each observation <span class="math inline">\(1, 2, \ldots, N\)</span>. The formula is then <span class="math display">\[\text{weighted mean} = \frac{\sum_{i=1}^N w_i \times x_i}{\sum_{i = 1}^N w_i}.\]</span> The ordinary mean is the special case of the weighted mean where the weight on every observation is the same: <span class="math inline">\(w_1 = w_2 = \cdots = w_N\)</span>.</p>
<p>To calculate a weighted mean in R, we use the <code>weighted.mean()</code> function. This takes two arguments: the vector of values that we are averaging, and then the weight to place on each observation.</p>
<div class="callout callout-style-default callout-note callout-titled" title="In-class exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
In-class exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Return to the problem of calculating Biden’s average margin by county in 2020. Now calculate a weighted mean, where the weight on each county is the number of votes cast there. How does this compare to the raw mean, and to his 4.5 percentage point national margin of victory? What do you learn from the comparison?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co"># [Write your answer here]</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<p>The other most common measure of central tendency for a continuous variable is the <strong>median</strong>. If the median of some variable is <span class="math inline">\(m\)</span>, that means half of the observations are less than or equal to <span class="math inline">\(m\)</span>, and half of the observations are greater than or equal to <span class="math inline">\(m\)</span>. We calculate the median in R with the <code>median()</code> function. For example, let’s look at the median number of votes cast across the counties in our data frame.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(df_county_pres<span class="sc">$</span>total_votes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11140</code></pre>
</div>
</div>
<p>You can imagine it this way: Suppose we lined up each row of the data frame in order by <code>total_votes</code>, lowest to highest. The row at exactly the halfway point would have 11,140 total votes.</p>
<p>The mean and the median differ in terms of their sensitivity to <span class="concept">outliers</span>, data points that are extremely far from typical. For example, imagine you had a sample of 100 people: 99 normal people and Elon Musk. Because Elon Musk’s net worth is $420 billion, the average net worth of this sample would be at least $4.2 billion. And yet it would be misleading, in a sense, to say the average person in the sample is a billionaire — really you have one mega-billionaire and 99 regular people. The median net worth of the sample would be much, much lower.</p>

<div class="no-row-height column-margin column-container"><div class="margin-aside">
<p>In case you’re curious: I could only find statistics at the household level, but the median net worth of an American household is $192,000.</p>
</div></div><p>Because the mean is sensitive to outliers and the median is not, you might think we should prefer the median over the mean as a measure of central tendency. I think it’s more complicated than that. There are some situations where you care about outliers!</p>
<div class="callout callout-style-default callout-note callout-titled" title="In-class exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
In-class exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>You are running analytics for a political campaign. You recently tested two different templates for texts seeking political donations. You sent both texts to 1,000 different phone numbers from your list of supporters:</p>
<ul>
<li>Template A yielded a median donation of $5 and a mean donation of $7.</li>
<li>Template B yielded a median donation of $0 (in other words, most receipients donated nothing) and a mean donation of $20.</li>
</ul>
<p>If your goal is to just maximize the total amount of money donated, which template would you recommend sending out to the full list of supporters?</p>
<blockquote class="blockquote">
<p>[Write your answer here]</p>
</blockquote>
</div>
</div>
<p>How competitive are recent presidential elections? Are they getting more or less competitive? Let’s take a few different calculations. Which one do you think best captures the competitiveness of each election?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>df_county_pres <span class="sc">|&gt;</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year) <span class="sc">|&gt;</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_pct_margin =</span> <span class="fu">mean</span>(pct_margin),</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_weighted_pct_margin =</span> <span class="fu">weighted.mean</span>(pct_margin, total_votes),</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">med_pct_margin =</span> <span class="fu">median</span>(pct_margin)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 4
   year avg_pct_margin avg_weighted_pct_margin med_pct_margin
  &lt;dbl&gt;          &lt;dbl&gt;                   &lt;dbl&gt;          &lt;dbl&gt;
1  2000         -0.170                 0.00517         -0.175
2  2004         -0.212                -0.0248          -0.226
3  2008         -0.148                 0.0726          -0.162
4  2012         -0.205                 0.0395          -0.234
5  2016         -0.308                 0.0210          -0.376
6  2020         -0.313                 0.0445          -0.380
7  2024         -0.323                -0.0279          -0.375</code></pre>
</div>
</div>
<p>It wouldn’t be a introductory stats class if I didn’t mention the <span class="concept">mode</span>, which is the single value that appears most commonly in the data. The mode is not very useful for continuous variables. For example, in our total votes variable, there are 16,941 distinct values observed. The most common is 3,930, as there just happen to be eight counties where this was the exact total of votes. Just because we get this exact total in eight out of 22,000+ observations doesn’t make it “typical” in any meaningful sense.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>df_county_pres <span class="sc">|&gt;</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(total_votes) <span class="sc">|&gt;</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">number =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(number))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 16,941 × 2
   total_votes number
         &lt;dbl&gt;  &lt;int&gt;
 1        3930      8
 2        1017      7
 3        1369      7
 4        2031      6
 5        3906      6
 6         928      5
 7        1110      5
 8        1390      5
 9        1434      5
10        1440      5
# ℹ 16,931 more rows</code></pre>
</div>
</div>
</section>
<section id="unordered-categorical-variables" class="level3" data-number="3.2.2">
<h3 data-number="3.2.2" class="anchored" data-anchor-id="unordered-categorical-variables"><span class="header-section-number">3.2.2</span> Unordered categorical variables</h3>
<p>A <span class="concept">categorical variable</span> is one with a discrete set of possible values. Usually these are stored as character strings in a data frame, though sometimes (like we saw in the previous unit with the “outcome” variable in the crisis data) people use numerical codes to represent different categories.</p>
<p>We say a categorical variable is <span class="concept">unordered</span> when none of the categories is “greater” or “less” than the others. For example, the <code>region</code> variable in our county-level election data has four categories: Midwest, Northeast, South, and West. Because no region is “more” or “less” than the others, this variable is unordered.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>df_county_pres <span class="sc">|&gt;</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(region) <span class="sc">|&gt;</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">number =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  region    number
  &lt;chr&gt;      &lt;int&gt;
1 Midwest     7391
2 Northeast   1560
3 South       9934
4 West        3208</code></pre>
</div>
</div>
<p>You can’t calculate a mean for an unordered categorical variable, because you can’t add up the values. Nor can you calculate a median, because you can’t put them in order. The only calculation you can make is the mode—the category with the most observations. In the example here, the modal region is the South.</p>
<p>I find it more informative to look at the <span class="concept">distribution</span> of values of an unordered categorical variable: what proportion of values fall into each category?</p>
<div class="callout callout-style-default callout-note callout-titled" title="In-class exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
In-class exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Add a <code>proportion</code> column to the above table of frequency counts for census region, then order it from highest proportion to lowest.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co"># [Write your answer here]</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</section>
<section id="ordered-categorical-variables" class="level3" data-number="3.2.3">
<h3 data-number="3.2.3" class="anchored" data-anchor-id="ordered-categorical-variables"><span class="header-section-number">3.2.3</span> Ordered categorical variables</h3>
<p>A categorical variable is <span class="concept">ordered</span> when the categories can be put in order from “least” to “most”. For example, every election cycle the <a href="https://www.cookpolitical.com/ratings/house-race-ratings">Cook Political Report</a> issues qualitative ratings of Congressional races:</p>
<ul>
<li>Likely Republican</li>
<li>Lean Republican</li>
<li>Toss-up</li>
<li>Lean Democrat</li>
<li>Likely Democrat</li>
</ul>
<p>Our county-level presidential elections data here contains an analogue of the Cook ratings in the <code>Competitiveness</code> column. It’s a 7-point scale where the lowest values most strongly favor Republicans, while the highest values most strongly favor Democrats.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>df_county_pres <span class="sc">|&gt;</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(competitiveness) <span class="sc">|&gt;</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">number =</span> <span class="fu">n</span>(),</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_dem_margin =</span> <span class="fu">mean</span>(pct_margin),</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">med_dem_margin =</span> <span class="fu">median</span>(pct_margin)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 4
  competitiveness number avg_dem_margin med_dem_margin
            &lt;dbl&gt;  &lt;int&gt;          &lt;dbl&gt;          &lt;dbl&gt;
1              -3  12891       -0.444         -0.429  
2              -2   2631       -0.152         -0.151  
3              -1   1371       -0.0714        -0.0719 
4               0   1502       -0.00178       -0.00250
5               1    916        0.0691         0.0686 
6               2   1073        0.147          0.146  
7               3   1709        0.405          0.329  </code></pre>
</div>
</div>
<p>With an ordered categorical variable, we can look at the mode and the distribution just like we did with an unordered categorical variable. We still can’t calculate a mean, because we can’t sensibly add and subtract values of a non-continuous variable. However, unlike with an unordered categorical variable, here it is also sensible to calculate the median.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(df_county_pres<span class="sc">$</span>competitiveness)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -3</code></pre>
</div>
</div>
<p>Closely tracking what we saw with vote shares by county, we see here that the median county leans strongly in favor of Republican candidates.</p>
<p>What if your raw data is coded as a character string — e.g., <code>"Strong Republican"</code>, <code>"Likely Republican"</code>, etc.? You can still calculate the mode and the distribution the same way you did with an unordered categorical variable. However, to calculate the median, you’ll need to convert the character categories to numbers using <code>case_when()</code>, then run the <code>median()</code> function on the numerical version.</p>
</section>
<section id="binary-variables" class="level3 page-columns page-full" data-number="3.2.4">
<h3 data-number="3.2.4" class="anchored" data-anchor-id="binary-variables"><span class="header-section-number">3.2.4</span> Binary variables</h3>
<p>A <span class="concept">binary variable</span> is a categorical variable that has exactly two categories. Binary variables are special because we can essentially treat them as if they were continuous, specifically by treating one category as 0 and the other as 1.</p>
<p>In our county-level presidential data, the indicator for whether the Democrat won the state is a binary variable, already coded in 0/1 format.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>df_county_pres <span class="sc">|&gt;</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(dem_win_state) <span class="sc">|&gt;</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">number =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  dem_win_state number
          &lt;dbl&gt;  &lt;int&gt;
1             0  15262
2             1   6831</code></pre>
</div>
</div>
<p>With a binary variable coded in 0/1 format, the mean tells us the proportion of observations that are a 1.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(df_county_pres<span class="sc">$</span>dem_win_state)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.309193</code></pre>
</div>
</div>
<p>This value indicates that in about 33% of the counties in our data, the Democrat won the presidential election in the state that year.</p>
<div class="callout callout-style-default callout-note callout-titled" title="In-class exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
In-class exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Create a new column with a binary variable that indicates whether the Democrat won the given <em>county</em>, rather than the state as a whole. What is its mean, and how do you interpret that?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="co"># [Write your answer here]</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<p>You can also calculate the median and the mode of a binary variable. These will be the same as each other: a median and mode of 1 if more than 50% of observations are 1, and 0 if less than 50% are.</p>

<div class="no-row-height column-margin column-container"><div class="margin-aside">
<p>In the rare case of a variable that’s <em>exactly</em> 50-50, the calculated median depends on precisely which algorithm you use. For our purposes we’re not going to worry about that sort of edge case.</p>
</div></div></section>
</section>
<section id="spread-how-far-from-the-central-tendency-is-typical" class="level2 page-columns page-full" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="spread-how-far-from-the-central-tendency-is-typical"><span class="header-section-number">3.3</span> Spread: How far from the central tendency is typical?</h2>
<p>Imagine two hypothetical states, both with 9 counties. Say the average margin for the Democratic candidate across counties is 2% in both states. Furthermore say the median is 2% in both states too. Then they must be pretty politically similar — right?</p>
<p>Not necessarily. One way to end up with a mean and median of 2% is for every county to be slightly left of center, as in our hypothetical State A.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>margins_state_a <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.01</span>, <span class="fl">0.01</span>, <span class="fl">0.01</span>, <span class="fl">0.01</span>, <span class="fl">0.02</span>, <span class="fl">0.03</span>, <span class="fl">0.03</span>, <span class="fl">0.03</span>, <span class="fl">0.03</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(margins_state_a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(margins_state_a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02</code></pre>
</div>
</div>
<p>But you could also end up with these same numbers if the state is wildly polarized between heavily Democratic and heavily Republican counties, as in our hypothetical State B.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>margins_state_b <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.40</span>, <span class="sc">-</span><span class="fl">0.30</span>, <span class="sc">-</span><span class="fl">0.25</span>, <span class="sc">-</span><span class="fl">0.20</span>, <span class="fl">0.02</span>, <span class="fl">0.20</span>, <span class="fl">0.30</span>, <span class="fl">0.36</span>, <span class="fl">0.45</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(margins_state_b)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(margins_state_b)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02</code></pre>
</div>
</div>
<p>If we only look at central tendency, these two places look the same. When we also examine the <span class="concept">spread</span>, as in the dispersion of values around the central tendency, we see important differences. Our hypothetical State B has much more spread in vote margins than our hypothetical State A. The goal for us now is to work through some precise quantitative measures of spread.</p>
<p>We’ll only look at measures of spread for continuous variables. Measures of spread for categorical variables do exist, but I honestly don’t find them particularly useful as data summaries.</p>

<div class="no-row-height column-margin column-container"><div class="margin-aside">
<p>The measure I’m most familiar with for categorical variables is <a href="https://en.wikipedia.org/wiki/Entropy_(information_theory)">information entropy</a>. It does come up sometimes in machine learning applications, but not for the analyses we’ll do in PSCI 2300.</p>
</div></div><section id="sec-standard-deviation" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1" class="anchored" data-anchor-id="sec-standard-deviation"><span class="header-section-number">3.3.1</span> Standard deviation</h3>
<p>By far the most common measure of spread for a continuous variable is the <span class="concept">standard deviation</span>. Very loosely, I think of the standard deviation as telling us “What’s a normal difference between a random observation and the average?”</p>
<div id="tbl-sd-surprise-factor" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-sd-surprise-factor-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3.1: Calculating the “surprise factor” for an observation by looking at how many standard deviations away from the mean it is.
</figcaption>
<div aria-describedby="tbl-sd-surprise-factor-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Distance from mean</th>
<th>How surprising?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Within 1 SD</td>
<td>Not surprising at all</td>
</tr>
<tr class="even">
<td>1–2 SDs away</td>
<td>Mildly surprising</td>
</tr>
<tr class="odd">
<td>2–3 SDs away</td>
<td>Rare, but not out of this world</td>
</tr>
<tr class="even">
<td>3+ SDs away</td>
<td><a href="https://imgflip.com/memegenerator/Surprised-Pikachu">SurprisedPikachu.jpg</a></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>We can calculate the standard deviation in R using the <code>sd()</code> function. Let’s look at variation in total votes by county.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(df_county_pres<span class="sc">$</span>total_votes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 44419.82</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(df_county_pres<span class="sc">$</span>total_votes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 135957.8</code></pre>
</div>
</div>
<p>So we have a mean of about 44K and a standard deviation of about 136K. The standard deviation is always measured in the same units as the underlying variable. Because our <code>total_votes</code> column is measured in number of votes, so is its standard deviation.</p>
<p>Let’s see how much of the data falls into my quick categorization from <a href="#tbl-sd-surprise-factor" class="quarto-xref">Table&nbsp;<span>3.1</span></a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>vote_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(df_county_pres<span class="sc">$</span>total_votes)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>vote_sd <span class="ot">&lt;-</span> <span class="fu">sd</span>(df_county_pres<span class="sc">$</span>total_votes)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>df_county_pres <span class="sc">|&gt;</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># New column: How many SDs from the mean is total_votes in this row?</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sd_from_mean =</span> (total_votes <span class="sc">-</span> vote_mean) <span class="sc">/</span> vote_sd) <span class="sc">|&gt;</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Categorization based on absolute distance from mean</span></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">category =</span> <span class="fu">case_when</span>(</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">abs</span>(sd_from_mean) <span class="sc">&lt;</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">"Within 1 SD"</span>,</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">abs</span>(sd_from_mean) <span class="sc">&lt;</span> <span class="dv">2</span> <span class="sc">~</span> <span class="st">"Within 1-2 SD"</span>,</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">abs</span>(sd_from_mean) <span class="sc">&lt;</span> <span class="dv">3</span> <span class="sc">~</span> <span class="st">"Within 2-3 SD"</span>,</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">abs</span>(sd_from_mean) <span class="sc">&gt;=</span> <span class="dv">3</span> <span class="sc">~</span> <span class="st">"Within 3+ SD"</span></span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">|&gt;</span></span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Count number in each categorization</span></span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(category) <span class="sc">|&gt;</span></span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">number =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Calculate proportion in each categorization</span></span>
<span id="cb37-18"><a href="#cb37-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">proportion =</span> number <span class="sc">/</span> <span class="fu">sum</span>(number))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  category      number proportion
  &lt;chr&gt;          &lt;int&gt;      &lt;dbl&gt;
1 Within 1 SD    20883     0.945 
2 Within 1-2 SD    624     0.0282
3 Within 2-3 SD    272     0.0123
4 Within 3+ SD     314     0.0142</code></pre>
</div>
</div>
<p>Here we see the vast majority of the data, 94% of counties, is within 1 standard deviation of the mean in terms of total votes. Only about 2.8% is within 1–2 SDs of the mean, and less than half of that is within 2–3 SDs.</p>
<div class="callout callout-style-default callout-note callout-titled" title="In-class exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
In-class exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Calculate the standard deviation of the Democratic candidate’s percentage margin across counties for each different election in the data. Do you notice any trends? What does this tell us about how elections are changing over time?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="co"># [Write your answer here]</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<p>I will admit that the formula for the standard deviation is kind of intense: <span id="eq-standard-deviation"><span class="math display">\[
\text{sd} = \sqrt{\frac{\sum_{i=1}^N (x_i - \bar{x})^2}{N - 1}}.
\tag{3.1}\]</span></span> Here’s what’s going on:</p>
<ul>
<li><p>We take each of the <span class="math inline">\(N\)</span> observations of our variable, <span class="math inline">\(x_1, x_2, \ldots, x_N\)</span>.</p></li>
<li><p>For each of these observations, <span class="math inline">\(x_i\)</span>, we find the difference between it and the mean: <span class="math inline">\(x_i - \bar{x}\)</span>.</p></li>
<li><p>We square each of those differences, so now they’re each a positive number, namely the squared distance between the observation and the mean: <span class="math inline">\((x_i - \bar{x})^2\)</span>.</p></li>
<li><p>We take the average of all the squared differences. Well, not <em>quite</em> the average, because for statistical reasons I won’t get into here, we divide the sum by <span class="math inline">\(N - 1\)</span> instead of <span class="math inline">\(N\)</span>. But with any moderately large sample, dividing by <span class="math inline">\(N - 1\)</span> has almost the same result as dividing by <span class="math inline">\(N\)</span> anyway.</p></li>
<li><p>We take the square root of the whole thing so that it’s measured in the same units as the original variable.</p></li>
</ul>
</section>
<section id="median-absolute-deviation" class="level3" data-number="3.3.2">
<h3 data-number="3.3.2" class="anchored" data-anchor-id="median-absolute-deviation"><span class="header-section-number">3.3.2</span> Median absolute deviation</h3>
<p>The standard deviation shares some of the same problems as the mean, namely a sensitivity to outliers. One single observation can make a huge difference to the standard deviation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a vector of evenly-spaced hypothetical data points</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">1</span>, <span class="at">to =</span> <span class="dv">2</span>, <span class="at">length.out =</span> <span class="dv">20</span>)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>x</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 1.000000 1.052632 1.105263 1.157895 1.210526 1.263158 1.315789 1.368421
 [9] 1.421053 1.473684 1.526316 1.578947 1.631579 1.684211 1.736842 1.789474
[17] 1.842105 1.894737 1.947368 2.000000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3113726</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Take same vector of data, but make a single outlier</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> x</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>y[<span class="dv">20</span>] <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>y</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  1.000000  1.052632  1.105263  1.157895  1.210526  1.263158  1.315789
 [8]  1.368421  1.421053  1.473684  1.526316  1.578947  1.631579  1.684211
[15]  1.736842  1.789474  1.842105  1.894737  1.947368 10.000000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(y)  <span class="co"># Will be way higher!</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.928213</code></pre>
</div>
</div>
<p>The <span class="concept">median absolute deviation</span> is to the standard deviation as the median is to the mean. It is another measure of spread that is less sensitive to outliers. We calculate it by going through the following steps:</p>
<ul>
<li><p>Calculate the median of the sample, call it <span class="math inline">\(m\)</span>.</p></li>
<li><p>Calculate the distance between each observation and the sample median: <span class="math inline">\(|x_i - m|\)</span>.</p></li>
<li><p>Take the median of these distances.</p></li>
</ul>
<p>We can calculate the median absolute deviation in R using the <code>mad()</code> function. There’s a kind of annoying default scaling option to try to make the MAD more similar to the standard deviation; I don’t like that, so I add the argument <code>constant = 1</code> to turn that off.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(df_county_pres<span class="sc">$</span>total_votes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11140</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mad</span>(df_county_pres<span class="sc">$</span>total_votes, <span class="at">constant =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7762</code></pre>
</div>
</div>
<p>This means half of the counties in the data have between 3,378 and 18,902 votes (median of 11,140, plus or minus the MAD of 7,762 votes).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>median_votes <span class="ot">&lt;-</span> <span class="fu">median</span>(df_county_pres<span class="sc">$</span>total_votes)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>mad_votes <span class="ot">&lt;-</span> <span class="fu">mad</span>(df_county_pres<span class="sc">$</span>total_votes, <span class="at">constant =</span> <span class="dv">1</span>)</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>df_county_pres <span class="sc">|&gt;</span></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Categorize each row:</span></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 1. below median - MAD</span></span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 2. above median - MAD, but below median + MAD</span></span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 3. above median + MAD</span></span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">category =</span> <span class="fu">case_when</span>(</span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a>    total_votes <span class="sc">&lt;</span> median_votes <span class="sc">-</span> mad_votes <span class="sc">~</span> <span class="st">"lower"</span>,</span>
<span id="cb52-11"><a href="#cb52-11" aria-hidden="true" tabindex="-1"></a>    total_votes <span class="sc">&lt;</span> median_votes <span class="sc">+</span> mad_votes <span class="sc">~</span> <span class="st">"middle"</span>,</span>
<span id="cb52-12"><a href="#cb52-12" aria-hidden="true" tabindex="-1"></a>    total_votes <span class="sc">&gt;=</span> median_votes <span class="sc">+</span> mad_votes <span class="sc">~</span> <span class="st">"upper"</span></span>
<span id="cb52-13"><a href="#cb52-13" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">|&gt;</span></span>
<span id="cb52-14"><a href="#cb52-14" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Count by category and calculate proportions</span></span>
<span id="cb52-15"><a href="#cb52-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(category) <span class="sc">|&gt;</span></span>
<span id="cb52-16"><a href="#cb52-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">number =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb52-17"><a href="#cb52-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">proportion =</span> number <span class="sc">/</span> <span class="fu">sum</span>(number))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  category number proportion
  &lt;chr&gt;     &lt;int&gt;      &lt;dbl&gt;
1 lower      3355      0.152
2 middle    11047      0.500
3 upper      7691      0.348</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="In-class exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
In-class exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Repeat the previous exercise, on the spread of the Democratic candidate’s percentage margin across counties by year, but now using the MAD instead of the standard deviation. Does the data tell the same big-picture story, or a different one?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="co"># [Write your answer here]</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</section>
<section id="sec-quartiles" class="level3 page-columns page-full" data-number="3.3.3">
<h3 data-number="3.3.3" class="anchored" data-anchor-id="sec-quartiles"><span class="header-section-number">3.3.3</span> Quartiles and other percentages</h3>
<p>Another common way to gauge the spread of a variable is to look at its <span class="concept">quartiles</span>:</p>
<ul>
<li><p>The first/lower quartile is the value that 25% of the data is below and 75% is above.</p></li>
<li><p>The second quartile is the value that 50% of the data is below and 50% is above. In other words, the second quartile is the median.</p></li>
<li><p>The third quartile is the value that 75% of the data is below and 25% is above.</p></li>
</ul>
<p>We can calculate quartiles using the <code>quantile()</code> function in R. Yes, they’re called quartiles with an “r”, yet we use <code>quantile()</code> with an “n”. (Typing <code>quartile()</code> for <code>quantile()</code> is one of my most frequent R mistakes.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(df_county_pres<span class="sc">$</span>total_votes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     0%     25%     50%     75%    100% 
     64    5073   11140   29674 5488998 </code></pre>
</div>
</div>
<p>This function also helpfully tells us the minimum and maximum. What we see here is that:</p>
<ul>
<li><p>The smallest quarter of counties had 64 to 5,073 votes cast.</p></li>
<li><p>The next quarter had 5,073 to 11,140 votes cast.</p></li>
<li><p>The next had 11,140 to 29,674 votes cast.</p></li>
<li><p>The largest quarter had 28,138 to 5,488,998 votes cast.</p></li>
</ul>

<div class="no-row-height column-margin column-container"><div class="margin-aside">
<p>I think the very largest value in the data is an error. It’s the 2024 value for Harris County, TX, home of Houston. The total population of the county is estimated to be about 5,000,000 — which includes children, noncitizens, and others ineligible to vote — and the sum of the Trump and Harris vote totals there is only about 2,750,000. Let this be a lesson on working with real-world data: take a careful look at data quality before trying to draw firm conclusions!</p>
</div></div><p>The difference between the third and first quartiles is called the <span class="concept">interquartile range</span>. You can calculate it in R with the <code>IQR()</code> function. Some people find this value useful, though frankly I don’t.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">IQR</span>(df_county_pres<span class="sc">$</span>total_votes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 24601</code></pre>
</div>
</div>
<p>The quartiles are special cases of <span class="concept">percentiles</span> of the data. For any number <span class="math inline">\(p\)</span> between 0 and 100, the <span class="math inline">\(p\)</span>’th percentile of the data is the value that <span class="math inline">\(p\)</span>% of the data is below and <span class="math inline">\((100-p)\)</span>% of the data is above. To calculate a percentile, we can again use the <code>quantile()</code> function. For example, let’s find the 95th percentile, separating the smallest 95% of counties from the largest 5%. Note that we have to specify the argument to <code>quantile()</code> in terms of a proportion (between 0 and 1) rather than a percentage (between 0 and 100).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(df_county_pres<span class="sc">$</span>total_votes, <span class="fl">0.95</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     95% 
196344.8 </code></pre>
</div>
</div>
<p>So we see that 95% counties had less than 196,344 votes cast, while 5% had more.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./data_wrangling.html" class="pagination-link" aria-label="Data Wrangling">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data Wrangling</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./data_visualization.html" class="pagination-link" aria-label="Data Visualization">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data Visualization</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p xmlns:cc="http://creativecommons.org/ns#" class="cc-footer">
This work is licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-NC-SA 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1" alt=""></a>
</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>